### ISSUE TITLE
[Bug]: Adding command 

### ISSUE THREAD

**Issue by jhnguyen521** [shadcn-ui/ui#2944]
### Describe the bug

When utilizing a Command component that has been added/updated as of 03/07/2024 ~6PM PST,
This is due to cmdk making a new release with breaking changes: https://github.com/pacocoursey/cmdk/releases

This can be fixed by pinning cmdk version to 0.2.1. Haven't investigated shadcn fix yet.

### Affected component/components

Command

### How to reproduce

1. Run `npx shadcn-ui@latest add command` after 03/07/2024
2. Try to use command component

### Codesandbox/StackBlitz link

https://codesandbox.io/p/devbox/shadcn-playground-forked-4xxqcw?workspaceId=2d1a1544-9936-4d36-a113-0092357e5e51

### System Info

```bash
cmdk v1.0.0
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by jhnguyen521** [comment]
Some notes, seems like <CommandItem> needs to be contained somewhere within a <CommandList>. <CommandGroup> is no longer sufficient. Upon doing this however, items are no longer selectable with shadcn/ui

**Comment by abdasis** [comment]
I'm face same issue

**Comment by matowang** [comment]
+1

**Comment by collinversluis** [comment]
I encountered a similar problem when using the Combobox, but in my situation, the issue wasn't that it was unclickable or "disabled"; rather, the application would crash whenever the Combobox was opened. This is what I ran into for anyone googling this error:

`TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
`

This is also solved by pinning cmdk version to 0.2.1 in package.json for now. Thanks @jhnguyen521

**Comment by jhnguyen521** [comment]
> I encountered a similar problem when using the Combobox, but in my situation, the issue wasn't that it was unclickable or "disabled"; rather, the application would crash whenever the Combobox was opened. This is what I ran into for anyone googling this error:
> 
> `TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator)) `
> 
> This is also solved by pinning cmdk version to 0.2.1 in package.json for now. Thanks @jhnguyen521

Hey, I forgot to put in the error, but this is likely because you don't have a `<CommandList>` enclosing your `<CommandItems>` as I mentioned above:
> Some notes, seems like <CommandItem> needs to be contained somewhere within a <CommandList>. <CommandGroup> alone is no longer sufficient. Upon doing this however, items are now disabled with shadcn/ui

**Comment by collinversluis** [comment]
> > I encountered a similar problem when using the Combobox, but in my situation, the issue wasn't that it was unclickable or "disabled"; rather, the application would crash whenever the Combobox was opened. This is what I ran into for anyone googling this error:
> > `TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator)) `
> > This is also solved by pinning cmdk version to 0.2.1 in package.json for now. Thanks @jhnguyen521
> 
> Hey, I forgot to put in the error, but this is likely because you don't have a `<CommandList>` enclosing your `<CommandItems>` as I mentioned above, the cmdk version seems to have changed this behavior.
> 
> Some of the examples for the Command component are incorrect (which I also copy-pastaed (: ) and don't use a `<CommandList>` which I've also updated in the PR:
> 
> > Some notes, seems like `<CommandItem>` needs to be contained somewhere within a `<CommandList>`. `<CommandGroup>` alone is no longer sufficient. Upon doing this however, items are now disabled with shadcn/ui
> 
> Try just putting a `<CommandList>` around your existing `<CommandGroup>`s under the Usage example here: https://ui.shadcn.com/docs/components/command

This is totally the issue, adding the  `<CommandList>`  around your `<CommandItem>`'s resolves the TypeError.

Any thought on if we should be wrapping `<CommandList>` above `<CommandGroup>` or below?

Updating the examples will resolve the crash issue for future users, but the "aria-disabled" breaking change will still need to be updated so anyone with this issue should keep 0.2.1 pinned in their package.json until https://github.com/shadcn-ui/ui/pull/2945 is merged by changing

`    "cmdk": "^1.0.0"
` or similar

to 

`    "cmdk": "0.2.1"`

Thanks again @jhnguyen521!

**Comment by shainegordon** [comment]
I also had to remove `data-[disabled]:pointer-events-none data-[disabled]:opacity-50` from here

```js
const CommandItem = React.forwardRef<
    React.ElementRef<typeof CommandPrimitive.Item>,
    React.ComponentPropsWithoutRef<typeof CommandPrimitive.Item>
>(({ className, ...props }, ref) => (
    <CommandPrimitive.Item
        ref={ref}
        className={cn(
            'relative flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none aria-selected:bg-accent aria-selected:text-accent-foreground data-[disabled]:pointer-events-none data-[disabled]:opacity-50',
            className,
        )}
        {...props}
    />
))
```

Which makes me then wonder, what was it doing in the first place :)

**Comment by jhnguyen521** [comment]
> Any thought on if we should be wrapping `<CommandList>` above `<CommandGroup>` or below?

I believe it should be above `<CommandGroup>` according to all the examples, additionally enclosing `<CommandEmpty>` but I think it works either way 🤷

**Comment by shainegordon** [comment]
> I also had to remove `data-[disabled]:pointer-events-none data-[disabled]:opacity-50` from here
> 
> ```js
> const CommandItem = React.forwardRef<
>     React.ElementRef<typeof CommandPrimitive.Item>,
>     React.ComponentPropsWithoutRef<typeof CommandPrimitive.Item>
> >(({ className, ...props }, ref) => (
>     <CommandPrimitive.Item
>         ref={ref}
>         className={cn(
>             'relative flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none aria-selected:bg-accent aria-selected:text-accent-foreground data-[disabled]:pointer-events-none data-[disabled]:opacity-50',
>             className,
>         )}
>         {...props}
>     />
> ))
> ```
> 
> Which makes me then wonder, what was it doing in the first place :)

Ignore this, I missed the post about changing to `data-[disabled='true']`, so I just replaced those classes accordingly

I''ve also moved the position of `<CommandList>` as per the examples, and my combo-box is working again as it should

**Comment by abolajibisiriyu** [comment]
like @shainegordon said, I had to adjust the styles to fix this 

```
const CommandItem = React.forwardRef<
  React.ElementRef<typeof CommandPrimitive.Item>,
  React.ComponentPropsWithoutRef<typeof CommandPrimitive.Item>
>(({ className, ...props }, ref) => (
  <CommandPrimitive.Item
    ref={ref}
    className={cn(
      "relative flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-base outline-none aria-selected:bg-accent aria-selected:text-accent-foreground data-[disabled='true']:pointer-events-none data-[disabled='true']:opacity-50",
      className
    )}
    {...props}
  />
));
```

note the change `data-[disabled='true']`

**Comment by benjamin-guibert** [comment]
I had the same issue when updating to `cmdk` v1. I resolved the issue following your advices:
- I added `CommandList` in the tree;
- I replaced `data-[disabled]` by `data-[disabled='true']`.

Thank you! 🙏🏻

**Comment by itxtoledo** [comment]
shadcn should lock the dependency version to avoid these bugs due to updates

**Comment by faintblack** [comment]
> +1 Onclick interactions doesn't work

Maybe you don't change all the data-[disabled] to data-[disabled='true'].
I'm facing the same issues, but when I see it again, I just change one data-[disabled], but it actually have two.
When I change it all, it works fine.

**Comment by Kqan1** [comment]
The solution I use:

In @/components/ui/command.tsx file, you can change the classname on line 120 as follows: "relative flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none aria-selected: bg-accent aria-selected:text-accent-foreground data-[disabled=true]:pointer-events-none data-[disabled=true]:opacity-50"

**Comment by Babailan** [comment]
The component was built on version 0.2.1, but it automatically updated to version 1.0.0, indicating a major release. This could be due to the automatic incrementation of major versions when installing shadcn

**Comment by Liberty34** [comment]
I had the same issue and fixed with
adding CommandList in the tree (check shadcn docs)
I replaced data-[disabled] by data-[disabled='true']. I just don't like that but it's working

**Comment by Babailan** [comment]
> I had the same issue and fixed with adding CommandList in the tree (check shadcn docs) I replaced data-[disabled] by data-[disabled='true']. I just don't like that but it's working

you can downgrade the **`cmdk`** into previous version 0.2.1

**Comment by ZubriQ** [comment]
> I had the same issue and fixed with adding CommandList in the tree (check shadcn docs) I replaced data-[disabled] by data-[disabled='true']. I just don't like that but it's working

This. Just wrapped my CommandGroup with CommandList and it works now...

**Comment by optimbro** [comment]
> I also had to remove `data-[disabled]:pointer-events-none data-[disabled]:opacity-50` from here
> 
> ```js
> const CommandItem = React.forwardRef<
>     React.ElementRef<typeof CommandPrimitive.Item>,
>     React.ComponentPropsWithoutRef<typeof CommandPrimitive.Item>
> >(({ className, ...props }, ref) => (
>     <CommandPrimitive.Item
>         ref={ref}
>         className={cn(
>             'relative flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none aria-selected:bg-accent aria-selected:text-accent-foreground data-[disabled]:pointer-events-none data-[disabled]:opacity-50',
>             className,
>         )}
>         {...props}
>     />
> ))
> ```
> 
> Which makes me then wonder, what was it doing in the first place :)

thanks for the solution, I also wonder this now 😂😂😂

**Comment by Malachite40** [comment]
Still getting this issue, the fixes listed above work - however clicking on a CommandItem doesn't close the popover, leaving a meh UX

**Comment by samofoke** [comment]
Tahnks for the solutions it works after removing  ```data-[disabled]:pointer-events-none data-[disabled]:opacity-50```
I wonder if this will be fixed soon.

**Comment by KhoaLee** [comment]
> Thanks for the solutions it works after removing `data-[disabled]:pointer-events-none data-[disabled]:opacity-50` I wonder if this will be fixed soon.

This is correct and I hope we will have an official fix soon in next version

**Comment by Armadillidiid** [comment]
I've used <CommandList /> to wrap both <CommandEmpty /> and <CommandGroup />, but I encountered an unusual issue. Upon inspecting my console, I've noticed a multiple warnings indicating that children within the <CommandItem /> components share the same key.

> Warning: Encountered two children with the same key, `44`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

This warning isn't isolated to just one item; it applies to all <CommandItem />. It appears that <CommandItem /> attempts to render twice with identical keys. I resolved this by appending the map index to my unique ID. The fact that this solution works confirms that the component mounts twice simultaneously.

That aside, there's a huge lag when the button is clicked to the popover appearing, further confirming my thesis.


```javascript
<PopoverContent className="w-[300px] p-0">
  <Command>
    <CommandInput placeholder="Search country..." />
    <CommandList>
      <CommandEmpty>No country found.</CommandEmpty>
      <CommandGroup>
        {countries.map((country, idx) => (
          <CommandItem
            key={`${country.value}-${idx.toString()}`} // without `idx`, you'll get duplicate key error
            value={country.label}
            onSelect={() => doStuff()}
            }}
          >
            {country.label}
          </CommandItem>
        ))}
      </CommandGroup>
    </CommandList>
  </Command>
</PopoverContent>

```

**Comment by Sholamide** [comment]
> 0.2.1

clicking on a CommandItem doesn't close the popover

**Comment by baxsm** [comment]
I've used `^0.2.0` in different projects, works great for me

**Comment by Sholamide** [comment]
> I've used `^0.2.0` in different projects, works great for me

Did you make any modifications to the CommandItem classnames?, here's mine;

 <CommandPrimitive.Item
    ref={ref}
    className={cn(
      "relative flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none aria-[selected='true']:bg-accent aria-[selected='true']:text-accent-foreground data-[disabled='true']:pointer-events-none data-[disabled='true']:opacity-50",
      className
    )}
    {...props}
  />

**Comment by baxsm** [comment]
This is what I have

```
const CommandItem = React.forwardRef<
  React.ElementRef<typeof CommandPrimitive.Item>,
  React.ComponentPropsWithoutRef<typeof CommandPrimitive.Item>
>(({ className, ...props }, ref) => (
  <CommandPrimitive.Item
    ref={ref}
    className={cn(
      "relative flex cursor-pointer select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none aria-selected:bg-accent aria-selected:text-accent-foreground data-[disabled]:pointer-events-none data-[disabled]:opacity-50",
      className
    )}
    {...props}
  />
));
```

As mentioned above by folks, the difference might be `data-[disabled='true']` as I only have `data-[disabled]` for this version. (^0.2.0)

**Comment by youneszahzouh** [comment]
> Figured out the issue, in cmdk changenotes: `The aria-disabled and aria-selected props will now be set to false, instead of being undefined in https://github.com/pacocoursey/cmdk/commit/c57e6b7f81a5796395c7a016d6b1b2aac9591973`
> 
> It seems that the data-disabled prop is also set to false whereas before the property would not exist at all until being disabled, and `data-[disabled]:pointer-events-none` will apply even for `data-disabled="false"`.
> 
> The fix is to replace `data-[disabled]` with `data-[disabled='true']`. This should be backwards compatible too! :) I see that shadcn/ui uses data-[disabled] in numerous places, may be worth fixing this behavior everywhere. Going to make a PR.



This works like a charm

**Comment by Danilo-A** [comment]
> Figured out the issue, in cmdk changenotes: `The aria-disabled and aria-selected props will now be set to false, instead of being undefined in https://github.com/pacocoursey/cmdk/commit/c57e6b7f81a5796395c7a016d6b1b2aac9591973`
> 
> It seems that the data-disabled prop is also set to false whereas before the property would not exist at all until being disabled, and `data-[disabled]:pointer-events-none` will apply even for `data-disabled="false"`.
> 
> The fix is to replace `data-[disabled]` with `data-[disabled='true']`. This should be backwards compatible too! :) I see that shadcn/ui uses data-[disabled] in numerous places, may be worth fixing this behavior everywhere. Going to make a PR.

Legend! Thank you 🙏

**Comment by ARiyou2000** [comment]
replace `data-[disabled]:` with `data-[disabled=true]:` in components/ui/command.tsx

https://stackoverflow.com/a/78308802/11438881

**Comment by zahidiqbalnbs** [comment]
@jhnguyen521  you are doing great job, such a motivation. I am working on creating Multiselect component in this fashion using Popover (radix-ui/shadcn) with cmdk 1.0.0 but facing the same TypeError issue.  I tried using multiple solution from above thread but none worked and issue is randomly occuring. Can you please have a look? 

Following is the code.

`import { Command as CommandPrimitive, useCommandState } from 'cmdk'
import { X } from 'lucide-react'
import * as React from 'react'
import { forwardRef, useEffect } from 'react'

import { Badge } from '@/components/shadcn/Badge'
import { Command, CommandGroup, CommandItem, CommandList } from '@/components/shadcn/Command'
import { cn } from '@/utils'

import { Popover, PopoverContent, PopoverTrigger } from './Popover'

export interface Option {
  value: string
  label: string
  disable?: boolean
  /** fixed option that can't be removed. */
  fixed?: boolean
  /** Group the options by providing key. */
  [key: string]: string | boolean | undefined
}

interface GroupOption {
  [key: string]: Option[]
}

interface MultiSelectProps {
  values?: string[]
  defaultOptions?: Option[]
  /** manually controlled options */
  options?: Option[]
  placeholder?: string
  /** Loading component. */
  loadingIndicator?: React.ReactNode
  /** Empty component. */
  emptyIndicator?: React.ReactNode
  /** Debounce time for async search. Only work with `onSearch`. */
  delay?: number
  triggerSearchOnFocus?: boolean
  /** async search */
  onSearch?: (value: string) => Promise<Option[]>
  onChange?: (values: string[]) => void
  /** Limit the maximum number of selected options. */
  maxSelected?: number
  /** When the number of selected options exceeds the limit, the onMaxSelected will be called. */
  onMaxSelected?: (maxLimit: number) => void
  /** Hide the placeholder when there are options selected. */
  hidePlaceholderWhenSelected?: boolean
  disabled?: boolean
  groupBy?: string
  className?: string
  badgeClassName?: string
  selectFirstItem?: boolean
  /** Allow user to create option when there is no option matched. */
  creatable?: boolean
  /** Props of `Command` */
  commandProps?: React.ComponentPropsWithoutRef<typeof Command>
  /** Props of `CommandInput` */
  inputProps?: Omit<React.ComponentPropsWithoutRef<typeof CommandPrimitive.Input>, 'value' | 'placeholder' | 'disabled'>
}

export interface MultiSelectRef {
  selectedValue: Option[]
  input: HTMLInputElement
  focus: () => void
}

export const useDebounce = <T,>(value: T, delay?: number): T => {
  const [debouncedValue, setDebouncedValue] = React.useState<T>(value)

  useEffect(() => {
    const timer = setTimeout(() => setDebouncedValue(value), delay || 500)

    return () => {
      clearTimeout(timer)
    }
  }, [value, delay])

  return debouncedValue
}

const transToGroupOption = (options: Option[], groupBy?: string) => {
  if (options.length === 0) {
    return {}
  }
  if (!groupBy) {
    return {
      '': options,
    }
  }

  const groupOption: GroupOption = {}
  options.forEach((option) => {
    const key = (option[groupBy] as string) || ''
    if (!groupOption[key]) {
      groupOption[key] = []
    }
    groupOption[key].push(option)
  })
  return groupOption
}

const removePickedOption = (groupOption: GroupOption, picked: Option[]) => {
  const cloneOption = JSON.parse(JSON.stringify(groupOption)) as GroupOption

  for (const [key, value] of Object.entries(cloneOption)) {
    cloneOption[key] = value.filter((val) => !picked.find((p) => p.value === val.value))
  }
  return cloneOption
}

const CommandEmpty = forwardRef<HTMLDivElement, React.ComponentProps<typeof CommandPrimitive.Empty>>(
  ({ className, ...props }, forwardedRef) => {
    const render = useCommandState((state) => state.filtered.count === 0)

    if (!render) return null

    return (
      <div
        ref={forwardedRef}
        className={cn('py-3 text-center text-sm', className)}
        // eslint-disable-next-line react/no-unknown-property
        cmdk-empty=""
        role="presentation"
        onFocus={() => alert()}
        {...props}
      />
    )
  },
)

CommandEmpty.displayName = 'CommandEmpty'

export const MultiSelect = React.forwardRef<MultiSelectRef, MultiSelectProps>(
  (
    {
      values,
      onChange,
      placeholder,
      defaultOptions: arrayDefaultOptions = [],
      options: arrayOptions,
      delay,
      onSearch,
      loadingIndicator,
      emptyIndicator,
      maxSelected = Number.MAX_SAFE_INTEGER,
      onMaxSelected,
      hidePlaceholderWhenSelected,
      disabled,
      groupBy,
      className,
      badgeClassName,
      selectFirstItem = true,
      creatable = false,
      triggerSearchOnFocus = false,
      commandProps,
      inputProps,
    }: MultiSelectProps,
    ref: React.Ref<MultiSelectRef>,
  ) => {
    const inputRef = React.useRef<HTMLInputElement>(null)
    const [open, setOpen] = React.useState(false)
    const [isLoading, setIsLoading] = React.useState(false)

    const getSelectedOptions = () =>
      (arrayDefaultOptions || arrayOptions).filter((option) => values?.includes(option.value))

    const [selected, setSelected] = React.useState<Option[]>(getSelectedOptions() || [])
    const [options, setOptions] = React.useState<GroupOption>(transToGroupOption(arrayDefaultOptions, groupBy))
    const [inputValue, setInputValue] = React.useState('')
    const debouncedSearchTerm = useDebounce(inputValue, delay || 500)

    React.useImperativeHandle(
      ref,
      () => ({
        selectedValue: [...selected],
        input: inputRef.current as HTMLInputElement,
        focus: () => inputRef.current?.focus(),
      }),
      [selected],
    )

    const handleUnselect = React.useCallback(
      (option: Option) => {
        const newOptions = selected.filter((s) => s.value !== option.value)
        setSelected(newOptions)
        onChange?.(newOptions.map(({ value }) => value))
      },
      [onChange, selected],
    )

    const handleKeyDown = React.useCallback(
      (e: React.KeyboardEvent<HTMLDivElement>) => {
        const input = inputRef.current
        if (input) {
          if (e.key === 'Delete' || e.key === 'Backspace') {
            if (input.value === '' && selected.length > 0) {
              handleUnselect(selected[selected.length - 1])
            }
          }
          // This is not a default behaviour of the <input /> field
          if (e.key === 'Escape') {
            input.blur()
          }
        }
      },
      [handleUnselect, selected],
    )

    useEffect(() => {
      if (values) {
        setSelected(getSelectedOptions())
      }
    }, [values])

    useEffect(() => {
      /** If `onSearch` is provided, do not trigger options updated. */
      if (!arrayOptions || onSearch) {
        return
      }
      const newOption = transToGroupOption(arrayOptions || [], groupBy)
      if (JSON.stringify(newOption) !== JSON.stringify(options)) {
        setOptions(newOption)
      }
    }, [arrayDefaultOptions, arrayOptions, groupBy, onSearch, options])

    useEffect(() => {
      const doSearch = async () => {
        setIsLoading(true)
        const res = await onSearch?.(debouncedSearchTerm)
        setOptions(transToGroupOption(res || [], groupBy))
        setIsLoading(false)
      }

      const exec = async () => {
        if (!onSearch || !open) return

        if (triggerSearchOnFocus) {
          await doSearch()
        }

        if (debouncedSearchTerm) {
          await doSearch()
        }
      }

      void exec()
    }, [debouncedSearchTerm, groupBy, open, triggerSearchOnFocus])

    const CreatableItem = () => {
      if (!creatable) return undefined

      const Item = (
        <CommandItem
          value={inputValue}
          className="cursor-pointer"
          onMouseDown={(e) => {
            e.preventDefault()
            e.stopPropagation()
          }}
          onSelect={(value: string) => {
            if (selected.length >= maxSelected) {
              onMaxSelected?.(selected.length)
              return
            }
            setInputValue('')
            const newOptions = [...selected, { value, label: value }]
            setSelected(newOptions)
            onChange?.(newOptions.map(({ value }) => value))
          }}
        >{`Create "${inputValue}"`}</CommandItem>
      )

      // For normal creatable
      if (!onSearch && inputValue.length > 0) {
        return Item
      }

      // For async search creatable. avoid showing creatable item before loading at first.
      if (onSearch && debouncedSearchTerm.length > 0 && !isLoading) {
        return Item
      }

      return undefined
    }

    const EmptyItem = React.useCallback(() => {
      if (!emptyIndicator) return undefined

      // For async search that showing emptyIndicator
      if (onSearch && !creatable && Object.keys(options).length === 0) {
        return (
          <CommandItem value="-" disabled>
            {emptyIndicator}
          </CommandItem>
        )
      }

      return <CommandEmpty>{emptyIndicator}</CommandEmpty>
    }, [creatable, emptyIndicator, onSearch, options])

    const selectables = React.useMemo<GroupOption>(() => removePickedOption(options, selected), [options, selected])

    /** Avoid Creatable Selector freezing or lagging when paste a long string. */
    const commandFilter = React.useCallback(() => {
      if (commandProps?.filter) {
        return commandProps.filter
      }

      if (creatable) {
        return (value: string, search: string) => {
          return value.toLowerCase().includes(search.toLowerCase()) ? 1 : -1
        }
      }
      // Using default filter in `cmdk`. We don't have to provide it.
      return undefined
    }, [creatable, commandProps?.filter])

    return (
      <Popover open={open} onOpenChange={setOpen}>
        <Command
          {...commandProps}
          onKeyDown={(e) => {
            handleKeyDown(e)
            commandProps?.onKeyDown?.(e)
          }}
          className={cn('overflow-visible bg-transparent', commandProps?.className)}
          shouldFilter={commandProps?.shouldFilter !== undefined ? commandProps.shouldFilter : !onSearch} // When onSearch is provided, we don't want to filter the options. You can still override it.
          filter={commandFilter()}
        >
          <PopoverTrigger onFocus={() => inputRef.current?.focus()}>
            <div
              className={cn(
                'group rounded-md border border-input p-[5px] text-base ring-offset-background focus-within:border-blue-700 focus-within:border-2',
                className,
              )}
            >
              <div className="flex flex-wrap gap-1 items-center">
                {selected.map((option) => {
                  return (
                    <Badge
                      key={option.value}
                      className={cn(badgeClassName)}
                      data-fixed={option.fixed}
                      data-disabled={disabled}
                      variant="subtle"
                    >
                      {option.label}
                      <button
                        className={cn(
                          'ml-1 rounded-full outline-none ring-offset-background focus:ring-2 focus:ring-ring focus:ring-offset-2',
                          (disabled || option.fixed) && 'hidden',
                        )}
                        onKeyDown={(e) => {
                          if (e.key === 'Enter') {
                            handleUnselect(option)
                          }
                        }}
                        onMouseDown={(e) => {
                          e.preventDefault()
                          e.stopPropagation()
                        }}
                        onClick={() => handleUnselect(option)}
                        type="button"
                      >
                        <X className="h-3 w-3 text-muted-foreground hover:text-foreground" />
                      </button>
                    </Badge>
                  )
                })}
                {/* Avoid having the "Search" Icon */}

                <CommandPrimitive.Input
                  {...inputProps}
                  ref={inputRef}
                  value={inputValue}
                  disabled={disabled}
                  onValueChange={(value) => {
                    setInputValue(value)
                    inputProps?.onValueChange?.(value)
                  }}
                  onBlur={(event) => {
                    setOpen(false)
                    inputProps?.onBlur?.(event)
                  }}
                  onFocus={(event) => {
                    setOpen(true)
                    triggerSearchOnFocus && onSearch?.(debouncedSearchTerm)
                    inputProps?.onFocus?.(event)
                  }}
                  placeholder={hidePlaceholderWhenSelected && selected.length !== 0 ? '' : placeholder}
                  className={cn(
                    'flex-1 bg-transparent outline-none placeholder:text-muted-foreground',
                    inputProps?.className,
                  )}
                />
              </div>
            </div>
          </PopoverTrigger>
          <PopoverContent className="p-0">
            <CommandGroup className="w-full rounded-md border bg-popover text-popover-foreground shadow-md outline-none animate-in">
              {isLoading ? (
                <>{loadingIndicator}</>
              ) : (
                <>
                  {EmptyItem()}
                  {CreatableItem()}
                  {!selectFirstItem && <CommandItem value="-" className="hidden" />}
                  {Object.entries(selectables).map(([key, dropdowns]) => (
                    <CommandList key={key} className="h-full overflow-auto">
                      <>
                        {dropdowns.map((option) => {
                          return (
                            <CommandItem
                              key={option.value}
                              value={option.value}
                              disabled={option.disable}
                              onMouseDown={(e) => {
                                e.preventDefault()
                                e.stopPropagation()
                              }}
                              onSelect={() => {
                                if (selected.length >= maxSelected) {
                                  onMaxSelected?.(selected.length)
                                  return
                                }
                                setInputValue('')
                                const newOptions = [...selected, option]
                                setSelected(newOptions)
                                onChange?.(newOptions.map(({ value }) => value))
                              }}
                              className={cn('cursor-pointer', option.disable && 'cursor-default text-muted-foreground')}
                            >
                              {option.label}
                            </CommandItem>
                          )
                        })}
                      </>
                    </CommandList>
                  ))}
                </>
              )}
            </CommandGroup>
          </PopoverContent>
        </Command>
      </Popover>
    )
  },
)

MultiSelect.displayName = 'MultiSelect'
`

Error appears randomly not every time [TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator)) which is very annoying and cannot go to production with cmdk 1.0.0.

Moreover I wrote a test case which always gets failed using this MultiSelect component.
This test case for sure failed every time with error [TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))] that catches the issue very easily.

 ```
 it('handles keyboard interactions', async () => {
    const onChange = vi.fn()
    const { getByRole } = render(
      <MultiSelect
        options={[
          { value: '1', label: 'Option 1' },
          { value: '2', label: 'Option 2' },
        ]}
        onChange={onChange}
      />,
    )
    const multiselectElement = getByRole('combobox')
    fireEvent.keyDown(multiselectElement, { key: 'ArrowDown' })
    fireEvent.keyDown(multiselectElement, { key: 'Enter' })
  }) 
```

Any help would be appreciated. Here is sandbox [link](https://codesandbox.io/p/sandbox/multiselect-radix-cmdk-ym8zmh)  Issue rarely happens but yes it happens, usually reproduced on backspace/enter pressed in combobox. But test case is failing that's catching the issue every time.

**Comment by vienpt** [comment]
This is work for me
```js
<FormField
  control={form.control}
  name="language"
  render={({ field, fieldState }) => (
    <FormItem className="flex flex-col">
      <FormLabelValidate
        label={'Language'}
        htmlFor="language"
        invalid={fieldState.invalid}
      />
      <Popover open={open} onOpenChange={setOpen}>
        <PopoverTrigger asChild>
          <FormControl>
            <Button
              variant="outline"
              role="combobox"
              className={cn(
                'w-[200px] justify-between',
                !field.value && 'text-muted-foreground',
              )}
            >
              {field.value
                ? languages.find(
                    (language) => language.value === field.value,
                  )?.label
                : 'Select language'}
              <CaretSortIcon className="ml-2 size-4 shrink-0 opacity-50" />
            </Button>
          </FormControl>
        </PopoverTrigger>
        <PopoverContent className="w-[200px] p-0">
          <Command>
            <CommandInput
              placeholder="Search language..."
              className="h-9"
            />
            <CommandList>
              <CommandEmpty>No language found.</CommandEmpty>
              <CommandGroup>
                {languages.map((language) => (
                  <CommandItem
                    value={language.label}
                    key={language.value}
                    onSelect={() => {
                      form.clearErrors('language')
                      form.setValue('language', language.value)
                      setOpen(false)
                    }}
                  >
                    {language.label}
                    <CheckIcon
                      className={cn(
                        'ml-auto size-4',
                        language.value === field.value
                          ? 'opacity-100'
                          : 'opacity-0',
                      )}
                    />
                  </CommandItem>
                ))}
              </CommandGroup>
            </CommandList>
          </Command>
        </PopoverContent>
      </Popover>
      <FormMessageValidate />
    </FormItem>
  )}
/>
```

**Comment by abdulApp** [comment]
> CommandList

I had the same issue but after adding CommandList around CommandItem solved the problem. However, I had to change the disabled to equal true ("data-[disabled=true]:pointer-events-none data-[disabled=true]:opacity-50" instead of  "data-[disabled]:pointer-events-none data-[disabled]:opacity-50") so I can select the value I want. 

(I hope this was a helpful 🙌)

**Comment by myudak** [comment]
so, are there any other solutions besides a hacky workaround?

**Comment by kyusungpark** [comment]
> This is work for me
> 
> ```js
> <FormField
>   control={form.control}
>   name="language"
>   render={({ field, fieldState }) => (
>     <FormItem className="flex flex-col">
>       <FormLabelValidate
>         label={'Language'}
>         htmlFor="language"
>         invalid={fieldState.invalid}
>       />
>       <Popover open={open} onOpenChange={setOpen}>
>         <PopoverTrigger asChild>
>           <FormControl>
>             <Button
>               variant="outline"
>               role="combobox"
>               className={cn(
>                 'w-[200px] justify-between',
>                 !field.value && 'text-muted-foreground',
>               )}
>             >
>               {field.value
>                 ? languages.find(
>                     (language) => language.value === field.value,
>                   )?.label
>                 : 'Select language'}
>               <CaretSortIcon className="ml-2 size-4 shrink-0 opacity-50" />
>             </Button>
>           </FormControl>
>         </PopoverTrigger>
>         <PopoverContent className="w-[200px] p-0">
>           <Command>
>             <CommandInput
>               placeholder="Search language..."
>               className="h-9"
>             />
>             <CommandList>
>               <CommandEmpty>No language found.</CommandEmpty>
>               <CommandGroup>
>                 {languages.map((language) => (
>                   <CommandItem
>                     value={language.label}
>                     key={language.value}
>                     onSelect={() => {
>                       form.clearErrors('language')
>                       form.setValue('language', language.value)
>                       setOpen(false)
>                     }}
>                   >
>                     {language.label}
>                     <CheckIcon
>                       className={cn(
>                         'ml-auto size-4',
>                         language.value === field.value
>                           ? 'opacity-100'
>                           : 'opacity-0',
>                       )}
>                     />
>                   </CommandItem>
>                 ))}
>               </CommandGroup>
>             </CommandList>
>           </Command>
>         </PopoverContent>
>       </Popover>
>       <FormMessageValidate />
>     </FormItem>
>   )}
> />
> ```

does scroll work for you?

**Comment by apethree** [comment]
For anyone new to community to resolve this you need to change this in:  components/ui/command.tsx
Where you installed the components not in the component you are building 🗡️ . Hopefully this help someone.
```
replace data-[disabled]: with data-[disabled=true]: in components/ui/command.tsx
```

**Comment by bowen0110** [comment]
the scrollbar doesn't work

**Comment by iamisti** [comment]
> I also had to remove `data-[disabled]:pointer-events-none data-[disabled]:opacity-50` from here
> 
> ```js
> const CommandItem = React.forwardRef<
>     React.ElementRef<typeof CommandPrimitive.Item>,
>     React.ComponentPropsWithoutRef<typeof CommandPrimitive.Item>
> >(({ className, ...props }, ref) => (
>     <CommandPrimitive.Item
>         ref={ref}
>         className={cn(
>             'relative flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none aria-selected:bg-accent aria-selected:text-accent-foreground data-[disabled]:pointer-events-none data-[disabled]:opacity-50',
>             className,
>         )}
>         {...props}
>     />
> ))
> ```
> 
> Which makes me then wonder, what was it doing in the first place :)

This is very interesting, because in tailwind, you cannot add multiple classes to different states, like hover/active/focus/disabled

**Comment by paulofabiano** [comment]
Nothing is working for me: scroll, field focus, items mouse over. It is just static and I've applied all workaround suggested in here. I'm using react 18 and nextjs 14.2.4

**Comment by tjhoo** [comment]
I'm on the same boat as @paulofabiano 

May I know what else need to be done beside downgrading  `cmdk` to 0.2.0?

**Comment by tjhoo** [comment]
> I'm on the same boat as @paulofabiano
> 
> May I know what else need to be done beside downgrading `cmdk` to 0.2It.0?

It should be working by downgrading `cmdk` to 0.2.0?
```
<Popover>
  <PopoverTrigger asChild>
    <Button>OK</Button>
  </PopoverTrigger>
  <PopoverContent>
    <Command>
      <CommandInput></CommandInput>
      <CommandList>
        <CommandItem key="1" onSelect={() => console.log("first")}>
          123
        </CommandItem>
        <CommandItem key="2" onSelect={() => console.log("second")}>
          456
        </CommandItem>
      </CommandList>
    </Command>
  </PopoverContent>
  ```

**Comment by tuanvt** [comment]
> replace `data-[disabled]:` with `data-[disabled=true]:` in components/ui/command.tsx
> 
> https://stackoverflow.com/a/78308802/11438881

This works well for me. 
`data-[disabled=true]:pointer-events-none data-[disabled=true]:opacity-50`

**Comment by othman316** [comment]
> Figured out the issue, in cmdk changenotes: `The aria-disabled and aria-selected props will now be set to false, instead of being undefined in https://github.com/pacocoursey/cmdk/commit/c57e6b7f81a5796395c7a016d6b1b2aac9591973`
> 
> It seems that the data-disabled prop is also set to false whereas before the property would not exist at all until being disabled, and `data-[disabled]:pointer-events-none` will apply even for `data-disabled="false"`.
> 
> The fix is to replace `data-[disabled]` with `data-[disabled='true']`. This should be backwards compatible too! :) I see that shadcn/ui uses data-[disabled] in numerous places, may be worth fixing this behavior everywhere. Going to make a PR.

Works perfectly. Thank you!

**Comment by televators** [comment]
Been hearing about Shadcn for a while, finally trying it out and one of the first components I try is buggy. Surprised this is still not fixed as of August. Thanks for the fix, though!

**Comment by RanitManik** [comment]
> ```js
> form.clearErrors('language')
> ```

saved me a lot of time. Thanks!

**Comment by OmarKhattab** [comment]
Seems like an issue still

**Comment by thomas-cruz** [comment]
I was playing around with the [first example Combobox from the docs](https://ui.shadcn.com/docs/components/combobox) and even after applying the fixes it still breaks.

**Comment by shainegordon** [comment]
> Tried going back to 0.2.0, still didn't work for me. Looks like I chose the wrong library

It’s an extremely simple fix, just do this - https://github.com/shadcn-ui/ui/issues/2944#issuecomment-1986062418

Rather don’t throw the baby out with the bath water, for a lot of use cases, this is actually an excellent “library”

**Comment by derrickstaten** [comment]
Still broken. I tried everything in this thread:

Removing `data-[disabled=true]:pointer-events-none` and `data-[disabled=true]:opacity-50`.

Pinning `"cmdk": "0.2.1"`

Using `onSelect`.

Now remembering that this is what caused me to drop shadcn on a previous project -- combobox is a nightmare. It's generally worked for me for everything else, so i'm not ready to abandon it yet. But I totally empathize with people who try out shadcn, can get the boilerplate combobox to work, and abandon the library.

**Comment by bdlowery** [comment]
Go into your `command.tsx` component and do this

```js
const CommandDialog = ({ children, ...props }: CommandDialogProps) => {
  return (
    <Dialog {...props}>
      <DialogContent className="overflow-hidden p-0">
        <Command className="[&_[cmdk-group-heading]]:px-2 [&_[cmdk-group-heading]]:font-medium [&_[cmdk-group-heading]]:text-zinc-500 [&_[cmdk-group]:not([hidden])_~[cmdk-group]]:pt-0 [&_[cmdk-group]]:px-2 [&_[cmdk-input-wrapper]_svg]:h-5 [&_[cmdk-input-wrapper]_svg]:w-5 [&_[cmdk-input]]:h-12 [&_[cmdk-item]]:px-2 [&_[cmdk-item]]:py-3 [&_[cmdk-item]_svg]:h-5 [&_[cmdk-item]_svg]:w-5">
            <CommandList>{children}</CommandList>
        </Command>
      </DialogContent>
    </Dialog>
 )
}
```

**Comment by javed24** [comment]
anybody got lucky with this issue? I'm well aware of the `data-[disabled=true]:pointer-events-none data-[disabled=true]:opacity-50` workaround, which, upon installing the command component I see that it already had it, so I didn't need to make the change. However, it crashes the moment I select an option. 

here's a sample usage:

```
   <FormField
          name="productTypes"
          render={({ field }) => (
            <FormItem>
              <FormLabel className="text-xs uppercase text-gray-400">
                Product Types
              </FormLabel>
              <FormControl>
                <div className="relative">
                  <Command onKeyDown={(e) => e.stopPropagation()}>
                    <CommandInput
                      placeholder="Select an option"
                      value={
                        options.find(
                          (opt) => opt.value === selectedOption,
                        )?.label || ''
                      }
                      onFocus={() => setIsOpen(true)}
                    />
                    {isOpen && (
                      <CommandList className="absolute z-10 w-full rounded-lg bg-white shadow-md">
                        <CommandEmpty>No options found.</CommandEmpty>
                        <CommandGroup>
                          {hardcodedOptions.map((option) => (
                            <CommandItem
                              key={option.value}
                              onSelect={() => handleSelectOption(option.value)}
                            >
                              {option.label}
                            </CommandItem>
                          ))}
                        </CommandGroup>
                      </CommandList>
                    )}
                  </Command>
                </div>
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
```

A bit strange to see that the issue is still there despite the particular `cmdk` related fixes being applied. Has anyone found a workaround? Not sure if downgrading to `0.2.1` is the right way to go here.

**Comment by seanpquig** [comment]
Any chance some of this behavior has resurfaced recently?  These comboboxes were working fine for me a 1-2 weeks ago and now I can't select any of the options, despite not making any related code changes or library upgrades.

My command component already has the `data-[disabled=true]` fix. It had been working fine for me on cmdk 1.0.0 and downgrading to 0.2.1 doesn't seem to fix it.

**Comment by seanpquig** [comment]
> Any chance some of this behavior has resurfaced recently? These comboboxes were working fine for me a 1-2 weeks ago and now I can't select any of the options, despite not making any related code changes or library upgrades.
> 
> My command component already has the `data-[disabled=true]` fix. It had been working fine for me on cmdk 1.0.0 and downgrading to 0.2.1 doesn't seem to fix it.

Still not sure what broke this for me, but I found a fix by adding the `modal` prop to the Popover component of my combobox:

```
<Popover modal open={open} onOpenChange={setOpen}>
```

**Comment by arvilmena** [comment]
if you have `close()` invocation inside the `onBlur` event, you need to delay it, or else your `onClick` side-effect won't run because the cmdk result is already removed due to the onBlur => close() trigger

**Comment by VietManh4112** [comment]
> > Any chance some of this behavior has resurfaced recently? These comboboxes were working fine for me a 1-2 weeks ago and now I can't select any of the options, despite not making any related code changes or library upgrades.
> > My command component already has the `data-[disabled=true]` fix. It had been working fine for me on cmdk 1.0.0 and downgrading to 0.2.1 doesn't seem to fix it.
> 
> Still not sure what broke this for me, but I found a fix by adding the `modal` prop to the Popover component of my combobox:
> 
> ```
> <Popover modal open={open} onOpenChange={setOpen}>
> ```

I managed to resolve the issue by removing the <PopoverPrimitive.Portal> inside popover.tsx

**Comment by unclebay143** [comment]
> > Any chance some of this behavior has resurfaced recently? These comboboxes were working fine for me a 1-2 weeks ago and now I can't select any of the options, despite not making any related code changes or library upgrades.
> > My command component already has the `data-[disabled=true]` fix. It had been working fine for me on cmdk 1.0.0 and downgrading to 0.2.1 doesn't seem to fix it.
> 
> Still not sure what broke this for me, but I found a fix by adding the `modal` prop to the Popover component of my combobox:
> 
> ```
> <Popover modal open={open} onOpenChange={setOpen}>
> ```

This fixed it for me! Thanks

**Comment by fullstackstef** [comment]
This resolved it for me:
`<Popover modal open={open} onOpenChange={setOpen}>`

But the issue I'm seeing now is the `CommandInput` component is not enabled nor does the search functionality work. Anyone else facing this issue? I'm using `cmdk@1.0.0`

**Comment by danboyle7** [comment]
> This resolved it for me: `<Popover modal open={open} onOpenChange={setOpen}>`
> 
> But the issue I'm seeing now is the `CommandInput` component is not enabled nor does the search functionality work. Anyone else facing this issue? I'm using `cmdk@1.0.0`

I am observing thie behaviour as well with cmdk@1.1.1

**Comment by thes4s67** [comment]
Seeing an issue as well -- clicking on the combo box does nothing but I can see the DOM change as if its working. I am using cmdk@1.1.1 and tried adding modal to Popover and removing the `PopoverPrimative.Portal` but it doesn't work for me.

**Comment by thes4s67** [comment]
> Seeing an issue as well -- clicking on the combo box does nothing but I can see the DOM change as if its working. I am using cmdk@1.1.1 and tried adding modal to Popover and removing the `PopoverPrimative.Portal` but it doesn't work for me.

Ok so I was just able to fix this by updating `button.tsx` to:

```
const Button = React.forwardRef<
  HTMLButtonElement,
  React.ComponentProps<'button'> &
    VariantProps<typeof buttonVariants> & {
      asChild?: boolean
    }
>(({ className, variant, size, asChild = false, ...props }, ref) => {
  const Comp = asChild ? Slot : 'button'

  return (
    <Comp
      ref={ref}
      data-slot="button"
      className={cn(buttonVariants({ variant, size, className }))}
      {...props}
    />
  )
})

Button.displayName = 'Button'

export { Button, buttonVariants }

```

In short, it needed a forwardRef

**Comment by myudak** [comment]
bruh its still doesnt work fuckk

**Comment by sibteali786** [comment]
> This resolved it for me: `<Popover modal open={open} onOpenChange={setOpen}>`
> 
> But the issue I'm seeing now is the `CommandInput` component is not enabled nor does the search functionality work. Anyone else facing this issue? I'm using `cmdk@1.0.0`

Seeing the same issue ? did anyone found any fix for this ?

**Comment by RijanDhakal** [comment]
I found the solution guys : 
Just add "pointer-events-auto" in the className and its working for mouse events.

    function  ComboboxItem({
    
    className,
    
    children,
    
    ...props
    
    }:  ComboboxPrimitive.Item.Props) {
    
    return (
    
    <ComboboxPrimitive.Item
    
    data-slot="combobox-item"
    
    className={cn(
    
    "pointer-events-auto data-highlighted:bg-accent data-highlighted:text-accent-foreground not-data-[variant=destructive]:data-highlighted:**:text-accent-foreground gap-2 rounded-md py-1 pr-8 pl-1.5 text-sm [&_svg:not([class*='size-'])]:size-4 relative flex w-full cursor-default items-center outline-hidden select-none data-[disabled]:pointer-events-none data-[disabled]:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0",
    
    className,
    
    )}
    
    {...props}
    
    >
    
    {children}
    
    <ComboboxPrimitive.ItemIndicator
    
    render={
    
    <span  className="pointer-events-none absolute right-2 flex size-4 items-center justify-center">
    
    <CheckIcon  className="pointer-events-none"  />
    
    </span>
    
    }
    
    />
    
    </ComboboxPrimitive.Item>
    
    );
    
    }
