### ISSUE TITLE
[bug]: shadcn-ui installation fails with Next.js 15

### ISSUE THREAD

**Issue by TaifurIslamAshraf** [shadcn-ui/ui#5557]
### Describe the bug

While initializing a new Next.js project with shadcn-ui using `npx shadcn@latest init`, the installation fails when attempting to install dependencies. The error occurs because @radix-ui/react-icons has a peer dependency requirement for "react@^16.x || ^17.x || ^18.x", but the project is using React 19.0.0-rc-69d4b800-20241021.

Error message:
npm error ERESOLVE unable to resolve dependency tree
npm error Found: react@19.0.0-rc-69d4b800-20241021
npm error Could not resolve dependency:
npm error peer react@"^16.x || ^17.x || ^18.x" from @radix-ui/react-icons@1.3.0

Current environment:
- Next.js 15
- React 19.0.0-rc-69d4b800-20241021
- npm (latest version)
- shadcn-ui (latest version)

The installation works fine with React 18, suggesting that @radix-ui/react-icons needs to be updated to support React 19 release candidates.

Potential solutions:
1. Update @radix-ui/react-icons peer dependencies to include React 19
2. Add a note in the documentation about React 19 compatibility
3. Add a version check in the CLI to warn users about React 19 compatibility issues

### Affected component/components

shadcn-ui installation fails

### How to reproduce

```
Steps to reproduce:

1. Create a new Next.js project with experimental features:
   ```bash
   npx create-next-app@latest my-app --typescript --tailwind --app
   ```

2. During the setup, select 'yes' for App Router and other default options

3. Navigate to the project directory:
bash
   cd my-app

4. Try to initialize shadcn-ui:
bash
   npx shadcn@latest init

5. Select configuration options:
   - Style: New York
   - Base color: Neutral
   - CSS variables: Yes

6. The installation will fail during the dependency installation step with the following error:

   npm error ERESOLVE unable to resolve dependency tree
   npm error Found: react@19.0.0-rc-69d4b800-20241021
   npm error Could not resolve dependency:
   npm error peer react@"^16.x || ^17.x || ^18.x" from @radix-ui/react-icons@1.3.0

You can verify the React version in your package.json: 
{
  "dependencies": {
    "react": "19.0.0-rc-69d4b800-20241021",
    "react-dom": "19.0.0-rc-69d4b800-20241021"
  }
}

### System Info

```bash
System Information:

Operating System:
- Windows 8
- Working in Command Prompt

Node Environment:
- Node.js version: v20.17.0
- npm version: v10.9.0

Project Dependencies:
- Next.js: 15
- React: 19.0.0-rc-69d4b800-20241021
- React DOM: 19.0.0-rc-69d4b800-20241021
- Typescript: ^5
- Tailwind CSS: ^3.4.1

CLI Versions:
- create-next-app: latest
- shadcn-ui CLI: latest (@shadcn/ui)

Additional Context:
- Fresh installation with default configurations
- Using App Router
- Project created with TypeScript and Tailwind CSS enabled
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by Gitstar-OC** [comment]
Yeah, it is also coming for me do you got any solution ?

**Comment by Gitstar-OC** [comment]
I need this urgently, is there any other solution for this ?

**Comment by Gitstar-OC** [comment]
Do you need a temporary solution for this ?

**Comment by needim** [comment]
you can use overrides for a temporary fix.

```json
"overrides": {
	"react": "$react",
	"react-dom": "$react-dom"
}
```

> [!WARNING]  
> This is just a temporary fix!

**Comment by dx1ded** [comment]
You can also use: `npm config set legacy-peer-deps true`

**Comment by Gitstar-OC** [comment]
> You can also use: `npm config set legacy-peer-deps true`

No, it did not work for me I tried it. I just cloned old next js project I created in previous week and started using it for development, will change to nextjs 15 after the pr is merged.

**Comment by Jacksonmills** [comment]
Hey @TaifurIslamAshraf,

I tested out this scenario and was able to get shadcn-ui running smoothly with the New York theme and the `@radix-ui/react-icons` package.

Here's what I did:
1. Created a repo with `npx shadcn/ui@latest init`, using New York as the style and including `@radix-ui/react-icons`.
2. Added some components with `npx shadcn/ui@latest add ...` and made sure to use some icons from `@radix-ui/react-icons`.
3. Verified everything ran fine in Next.js 14.
4. Ran the codemod to upgrade: `npx @next/codemod@canary upgrade latest`.
5. Placed an `@radix-ui/react-icons` icon on the homepage for testing.

Everything worked both locally and in production without issues.

Prod links:
[Home page](https://shadcn-10-24-24-02-75vntjjr3-jems-projects-ab6283f6.vercel.app/)
[Dashboard page](https://shadcn-10-24-24-02-75vntjjr3-jems-projects-ab6283f6.vercel.app/dashboard)

For reference, here are some key details about my setup:
- Next.js: 15.0.1
- React: 19.0.0-rc-69d4b800-20241021
- React DOM: 19.0.0-rc-69d4b800-20241021
- `@radix-ui/react-icons`: ^1.3.0
- Tailwind CSS: ^3.4.1
- TypeScript: ^5
- Node.js: v20.17.0
- npm: v10.9.0

Feel free to check out the repo directly here: [GitHub Repo](https://github.com/Jacksonmills/shadcn-10-24-24-02) to make sure everything is set up correctly. Let me know if you need more details or if there's anything else I can help test!

**Comment by audionai** [comment]
i got this like error but u can fic in package.json
react version must less that 18;
and also react dom less 18;
  "devDependencies": {
    "@types/node": "^20", 
    "@types/react": "^18",  <<here
    "@types/react-dom": "^18",
    "eslint": "^8",

**Comment by Allan2000-Git** [comment]
Solution is to install `react@18` and `react-dom@18`. It'll temporarily solve the issue.

**Comment by Alienimnida** [comment]
I keep getting this error what should I do?

**Comment by TaifurIslamAshraf** [comment]
I found a solution. Use pnpm package manager

**Comment by Alienimnida** [comment]
Just using pnpm solves it?

**Comment by TaifurIslamAshraf** [comment]
Yes

**Comment by Jacksonmills** [comment]
I guess that's why my setup had no issues then

**Comment by Alienimnida** [comment]
Nahh man it must be due to the new release ig

**Comment by tutorialsmaterials** [comment]
check blog solve this problem 
https://tutorialsmaterial.com/post/ShadCn-Nextjs-15

**Comment by shadcn** [comment]
Can someone confirm if this it works with `pnpm` please? 

`pnpm dlx shadcn@latest init`

**Comment by amitb0ra** [comment]
> pnpm dlx shadcn@latest init

![image](https://github.com/user-attachments/assets/1c90a85c-7db7-409a-a6c3-278b81c78f39)

**Comment by shadcn** [comment]
@amitb0ra Seems to be a different (permission) issue.

**Comment by amitb0ra** [comment]
> @amitb0ra Seems to be a different (permission) issue.

i tried with admin terminal. but got same error.

**Comment by Programmer118** [comment]
You can solve this issue by installing react 18 .
I tried and it's working fine for me

**Comment by shadcn** [comment]
@Jacksonmills prod. thanks.

(Yes it looks like it's working but I have a fix on the way as well)

**Comment by raheelk2k** [comment]
> Can someone confirm if this it works with `pnpm` please?
> 
> `pnpm dlx shadcn@latest init`

I tried it doesn't

**Comment by AnticharppiScalboost** [comment]
Same here

> > Can someone confirm if this it works with `pnpm` please?
> > `pnpm dlx shadcn@latest init`
> 
> I tried it doesn't

Same here

**Comment by Jacksonmills** [comment]
What is the output/errors you all are getting?

**Comment by AnticharppiScalboost** [comment]
> What is the output/errors you all are getting?

This is the full error:

I decided to try in a fresh nextjs project. 

`npx create-next-app test-shadcn`

Then install shadcn

`npx shadcn@latest init`

The above command throws me this error:
```
Something went wrong. Please check the error below for more details.
If the problem persists, please open an issue on GitHub.

Command failed with exit code 1: npm install tailwindcss-animate class-variance-authority lucide-react @radix-ui/react-icons clsx tailwind-merge
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: test-shadcn@0.1.0
npm error Found: react@19.0.0-rc-69d4b800-20241021
npm error node_modules/react
npm error   react@"19.0.0-rc-69d4b800-20241021" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@"^16.x || ^17.x || ^18.x" from @radix-ui/react-icons@1.3.0
npm error node_modules/@radix-ui/react-icons
npm error   @radix-ui/react-icons@"^1.3.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
```

As temporal fix, it worked to execute [this](https://github.com/shadcn-ui/ui/issues/5557#issuecomment-2436168147) command

**Comment by luisbustalu** [comment]
> Can someone confirm if this it works with `pnpm` please?
> 
> `pnpm dlx shadcn@latest init`

Works in my side.

**Comment by bobbyy16** [comment]
Use Nextjs 14

npx create-next-app@14

**Comment by shadcn** [comment]
Update: https://ui.shadcn.com/docs/react-19. Please take a look and let me know. Thank you.

**Comment by Jacksonmills** [comment]
> Update: https://ui.shadcn.com/docs/react-19. Please take a look and let me know. Thank you.

Tried out the latest changes:
1. `npx create-next-app@latest my-app`
2. `npx shadcn@latest init` with `--force` and `--legacy-peer-deps`

All good on my end. Just a heads up for docs—if someone uses npm/npx, they'll need to add `--force` or `--legacy-peer-deps` whenever they install stuff manually, at least for now. Tried it with pnpm too, and it works the same as before, no issues.

Let me know if there's anything else you want me to check!

**Comment by Jacksonmills** [comment]
btw it looks like https://github.com/radix-ui/icons/pull/184 got merged so just `cmdk` it seems

**Comment by gitpush-gitpaid** [comment]
> Update: https://ui.shadcn.com/docs/react-19. Please take a look and let me know. Thank you.

wrong link in the shadcn docs
https://ui.shadcn.com/docs/installation/next

Leads to a 404
![Screenshot 2024-10-29 at 5 44 33 PM](https://github.com/user-attachments/assets/55b05599-0361-4e23-8e46-78289772afdf)

**Comment by AdiCahyaSaputra** [comment]
![image](https://github.com/user-attachments/assets/71da96a4-c71e-406b-b237-e811e592374a)

i'm using nextjs 15 with react@18 and react-dom@18... every component that need @radix-ui/react-primitive will be cause an error like this..

this is error from terminal 

![image](https://github.com/user-attachments/assets/ca0e15f1-f1e6-49c9-8628-09dc3e67fa31)

is there any solution for this ?

**Comment by wilfreddenton** [comment]
@Jacksonmills did this https://github.com/radix-ui/icons/pull/184 work for you? It did not fix it for me:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: horizon-market@0.1.0
npm ERR! Found: react@19.0.0-rc-02c0e824-20241028
npm ERR! node_modules/react
npm ERR!   react@"19.0.0-rc-02c0e824-20241028" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.x || ^17.x || ^18.x || ^19.x" from @radix-ui/react-icons@1.3.1
npm ERR! node_modules/@radix-ui/react-icons
npm ERR!   @radix-ui/react-icons@"^1.3.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /Users/wilfred/.npm/_logs/2024-10-30T20_46_44_479Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/wilfred/.npm/_logs/2024-10-30T20_46_44_479Z-debug-0.log
```

I think `19.0.0-rc` needs to be explicitly in peer dep list?

**Comment by Jacksonmills** [comment]
> @Jacksonmills did this [radix-ui/icons#184](https://github.com/radix-ui/icons/pull/184) work for you? It did not fix it for me:
> 
> ```
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR!
> npm ERR! While resolving: horizon-market@0.1.0
> npm ERR! Found: react@19.0.0-rc-02c0e824-20241028
> npm ERR! node_modules/react
> npm ERR!   react@"19.0.0-rc-02c0e824-20241028" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer react@"^16.x || ^17.x || ^18.x || ^19.x" from @radix-ui/react-icons@1.3.1
> npm ERR! node_modules/@radix-ui/react-icons
> npm ERR!   @radix-ui/react-icons@"^1.3.1" from the root project
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR!
> npm ERR!
> npm ERR! For a full report see:
> npm ERR! /Users/wilfred/.npm/_logs/2024-10-30T20_46_44_479Z-eresolve-report.txt
> 
> npm ERR! A complete log of this run can be found in: /Users/wilfred/.npm/_logs/2024-10-30T20_46_44_479Z-debug-0.log
> ```
> 
> I think `19.0.0-rc` needs to be explicitly in peer dep list?

are you using npm? and you used one of the `--force` or `--legacy-peer-deps`?

**Comment by wilfreddenton** [comment]
I am using npm and have been using `--force` to get past these errors. I was under the impression that updating to `1.3.1` would allow me to not have to use `--force` anymore.

**Comment by Jacksonmills** [comment]
It could be its not released yet on radix side, not quite sure

**Comment by Jacksonmills** [comment]
updated react-icons on my test repo and everything seems fine if I --force

![image](https://github.com/user-attachments/assets/a0f6c93c-516c-468d-a1ea-d1b5cd5fe156)

**Comment by Abenezer-berhanu** [comment]
i add shad cn components with --legacy-peer-deps and in development it works very well as well as when i build it locally it used to work as it expected but when i try to deploy it on vercel it's giving me the error 

![photo_2024-10-31_12-33-33](https://github.com/user-attachments/assets/fe90ecef-f0a3-4c96-8d61-d476d96f0124)

**Comment by tsemachh** [comment]
@shadcn - looks like https://github.com/pacocoursey/cmdk/pull/318 was merged and release was issued when are we going to have this in shadcn release?

**Comment by Jacksonmills** [comment]
> i add shad cn components with --legacy-peer-deps and in development it works very well as well as when i build it locally it used to work as it expected but when i try to deploy it on vercel it's giving me the error
> 
> ![photo_2024-10-31_12-33-33](https://private-user-images.githubusercontent.com/120560290/381898541-fe90ecef-f0a3-4c96-8d61-d476d96f0124.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzODkyNzMsIm5iZiI6MTczMDM4ODk3MywicGF0aCI6Ii8xMjA1NjAyOTAvMzgxODk4NTQxLWZlOTBlY2VmLWYwYTMtNGM5Ni04ZDYxLWQ0NzZkOTZmMDEyNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQxNTM2MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTQ2MjczZjY5NDJmNThjZjM2YWQ2OTA2MjJlNmM0MWFlYzU5OGUzZGE5MDViYjRhYmRmNDUwODg5NTJkOGM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cdib2R8rQD0gHdmDJJWVdII7kqj4HwVRj94mXG-qLc4)

you will need to make sure your build command is also set to `npm install --force/--legacy-peer-deps`

links to prod example:
https://shadcn-10-29-24-04.vercel.app/
https://shadcn-10-29-24-04.vercel.app/dashboard

![image](https://github.com/user-attachments/assets/61286560-be6d-4de9-9754-dc76d52d4db1)

**Comment by travisluong** [comment]
is there a way to skip the interactive prompt that asks for `--force` or `--legacy-peer-deps`? the `-y` flag to skip confirmation doesn't seem to work. i need to be able to run the `init` command and `add` command programmatically without the prompt coming up.

**Comment by irfanbakhtiar** [comment]
> You can also use: `npm config set legacy-peer-deps true`

Thanks, it works.

**Comment by shadcn** [comment]
@Jacksonmills thanks for the detailed write-up. I’m surprised this is still an issue. Tested this a few times yesterday. I’ll take a look.

**Comment by Jacksonmills** [comment]
> @Jacksonmills thanks for the detailed write-up. I’m surprised this is still an issue. Tested this a few times yesterday. I’ll take a look. 

Let me know if I can help test anything specific if needed

**Comment by lanzclintonv** [comment]
I'm also having this issue when creating from a new Next JS project. Confirmed that this happens with v2.1.4 via `npx shadcn@2.1.4 init`.

v2.1.3 works fine and allows me to select --force or --legacy-peer-deps

**Comment by shadcn** [comment]
I'm bringing back the flags (temporarily).

**Comment by rishi-novo** [comment]
<img width="996" alt="Screenshot 2024-11-05 at 3 15 56 PM" src="https://github.com/user-attachments/assets/1b0cec79-17e7-41d0-a662-26d536727332">

Does this issue still exists or am I messing up with something?

**Comment by souvik-basak** [comment]
I’m unsure what went wrong with shadcn; it also doesn't work with the previous version of next.js. I am using version `14.2.16`.

![image](https://github.com/user-attachments/assets/426d5db1-98e5-4a0d-a986-06540def377b)

**Comment by Jacksonmills** [comment]
> <img alt="Screenshot 2024-11-05 at 3 15 56 PM" width="996" src="https://private-user-images.githubusercontent.com/106062410/383091689-1b0cec79-17e7-41d0-a662-26d536727332.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MTY0NjcsIm5iZiI6MTczMDgxNjE2NywicGF0aCI6Ii8xMDYwNjI0MTAvMzgzMDkxNjg5LTFiMGNlYzc5LTE3ZTctNDFkMC1hNjYyLTI2ZDUzNjcyNzMzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxNDE2MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWMwMzhjYWM0NzdlY2IxMzA4ZGVkMjE5M2I2YjAwM2U0M2Q3YjM2ZDY1ZDc3ZjQwMmY3YmQwZWRmODU5YmU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rzqxZIh2O4ueScg9CWuw11PA-g7wSPVESRkuX1MUv_8">
> Does this issue still exists or am I messing up with something?

I cannot reproduce this error, here's what I did:
1. `pnpm dlx create-next-app@latest`
2. `pnpm dlx shadcn@latest init`

Maybe try again today

**Comment by jdhrivas** [comment]
what about if you have an existing project and upgraded to nextjs15? 
`Command failed with exit code 1: npm install @radix-ui/react-toast
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: @apollo/experimental-nextjs-app-support@0.11.3
npm error Found: next@15.0.2
npm error node_modules/next
npm error   peer next@"^14.0.0-0 || ^15.0.0-0" from next-auth@5.0.0-beta.25
npm error   node_modules/next-auth
npm error     next-auth@"^5.0.0-beta.25" from the root project
npm error   next@"^15.0.2" from the root project
npm error
npm error Could not resolve dependency:
npm error peer next@"^13.4.1 || ^14.0.0 || 15.0.0-rc.0" from @apollo/experimental-nextjs-app-support@0.11.3
npm error node_modules/@apollo/experimental-nextjs-app-support
npm error   @apollo/experimental-nextjs-app-support@"^0.11.3" from the root project
npm error
npm error Conflicting peer dependency: next@15.0.0-rc.0
npm error node_modules/next
npm error   peer next@"^13.4.1 || ^14.0.0 || 15.0.0-rc.0" from @apollo/experimental-nextjs-app-support@0.11.3
npm error   node_modules/@apollo/experimental-nextjs-app-support
npm error     @apollo/experimental-nextjs-app-support@"^0.11.3" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.`

I tried to init and I'm still getting the same errors

**Comment by jdhrivas** [comment]
The issue I noticed is not related to shadcn-ui but other dependencies and is prevents schadcn-ui adding components or init

```
Something went wrong. Please check the error below for more details.
If the problem persists, please open an issue on GitHub.

Command failed with exit code 1: npm install @radix-ui/react-toast
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: @apollo/experimental-nextjs-app-support@0.11.3
npm error Found: next@15.0.2
npm error node_modules/next
npm error   peer next@"^14.0.0-0 || ^15.0.0-0" from next-auth@5.0.0-beta.25
npm error   node_modules/next-auth
npm error     next-auth@"^5.0.0-beta.25" from the root project
npm error   next@"^15.0.2" from the root project
npm error
npm error Could not resolve dependency:
npm error peer next@"^13.4.1 || ^14.0.0 || 15.0.0-rc.0" from @apollo/experimental-nextjs-app-support@0.11.3
npm error node_modules/@apollo/experimental-nextjs-app-support
npm error   @apollo/experimental-nextjs-app-support@"^0.11.3" from the root project
npm error
npm error Conflicting peer dependency: next@15.0.0-rc.0
npm error node_modules/next
npm error   peer next@"^13.4.1 || ^14.0.0 || 15.0.0-rc.0" from @apollo/experimental-nextjs-app-support@0.11.3
npm error   node_modules/@apollo/experimental-nextjs-app-support
npm error     @apollo/experimental-nextjs-app-support@"^0.11.3" from the root project
```
In my case `npm config set legacy-peer-deps true` resolved the issue.

**Comment by shadcn** [comment]
@rishi-novo @souvik-basak I can't reproduce. can you access https://ui.shadcn.com/r/styles/default/utils.json?

**Comment by nemanjam** [comment]
Why `npx shadcn@latest init` just installs Next.js 14 and React 18, nothing is updated?

**Comment by jasonjos111** [comment]
I am also facing the installation error 
There is no problem for most of the components but for some components like 'Alert Dialog' , I am getting this error 
```
# npm resolution error report

While resolving: next-auth@4.24.8
Found: next@15.0.3
node_modules/next
  next@"^15.0.3" from the root project

Could not resolve dependency:
peer next@"^12.2.5 || ^13 || ^14" from next-auth@4.24.8
node_modules/next-auth
  next-auth@"^4.24.8" from the root project

Conflicting peer dependency: next@14.2.17
node_modules/next
  peer next@"^12.2.5 || ^13 || ^14" from next-auth@4.24.8
  node_modules/next-auth
    next-auth@"^4.24.8" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
```
Any help?

**Comment by Abood2284** [comment]
I believe ShadCN is not stable with the latest NextJs 15 release

I can not add components, but some specific components are throwing random errors

~ button : bunx --bun shadcn@latest add button
<img width="955" alt="Screenshot 2024-11-11 at 6 43 23 PM" src="https://github.com/user-attachments/assets/da029df8-90ab-4dac-b791-7afb01587037">

<img width="841" alt="Screenshot 2024-11-11 at 6 43 41 PM" src="https://github.com/user-attachments/assets/15145e56-d1d5-4dde-99c5-02446ea33a1b">


~ alert dialog: bunx --bun shadcn@latest add alert-dialog
<img width="980" alt="Screenshot 2024-11-11 at 6 44 06 PM" src="https://github.com/user-attachments/assets/bfbcb1e8-9a9e-4c48-ad03-cc72a75ea27f">

Whole file is diagnosed with errors

any help?

**Comment by jasonjos111** [comment]
> I believe ShadCN is not stable with the latest NextJs 15 release
> 
> I can not add components, but some specific components are throwing random errors
> 
> ~ button : bunx --bun shadcn@latest add button <img alt="Screenshot 2024-11-11 at 6 43 23 PM" width="955" src="https://private-user-images.githubusercontent.com/90205565/384934463-da029df8-90ab-4dac-b791-7afb01587037.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMzIyNDYsIm5iZiI6MTczMTMzMTk0NiwicGF0aCI6Ii85MDIwNTU2NS8zODQ5MzQ0NjMtZGEwMjlkZjgtOTBhYi00ZGFjLWI3OTEtN2FmYjAxNTg3MDM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDEzMzIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5MjZiODBiNDc2MzgxYjg5MDBmMDllNTA3NTRkYzk5ZTVjNzU5OGUxNWE2OTAxMDRhODVjY2YyZDg5MGI2NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6wW3iKt-DspX3lxIB1hUYgv2NVgarBWWVQGn5tekmGY">
> 
> <img alt="Screenshot 2024-11-11 at 6 43 41 PM" width="841" src="https://private-user-images.githubusercontent.com/90205565/384934546-15145e56-d1d5-4dde-99c5-02446ea33a1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMzIyNDYsIm5iZiI6MTczMTMzMTk0NiwicGF0aCI6Ii85MDIwNTU2NS8zODQ5MzQ1NDYtMTUxNDVlNTYtZDFkNS00ZGRlLTk5YzUtMDI0NDZlYTMzYTFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDEzMzIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzYjI2MjQ5NWZjNjcxZTljMGM4Mjg0YWFjYjI2ZGUwMDhhYjQyZGMwZDg2NWFlZDI3MWI0YTk3NDY3NDMwNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Io0E3gEfaTgohMhvlGyA5DJfmLCtrS4jGtyc1TiDCQY">
> ~ alert dialog: bunx --bun shadcn@latest add alert-dialog <img alt="Screenshot 2024-11-11 at 6 44 06 PM" width="980" src="https://private-user-images.githubusercontent.com/90205565/384934650-bfbcb1e8-9a9e-4c48-ad03-cc72a75ea27f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMzIyNDYsIm5iZiI6MTczMTMzMTk0NiwicGF0aCI6Ii85MDIwNTU2NS8zODQ5MzQ2NTAtYmZiY2IxZTgtOWE5ZS00YzQ4LWFkMDMtY2M3MmE3NWVhMjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDEzMzIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2MWViNmJkMWY4YTM2MDg0MzNkODE3OTg3Mjc1ZDI0NzBmZmRiY2FmZGJiYzRmMWMyYjhiYzBmZTZlMTMzNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WuHzADt5eBJv52jfZ4MoVaDK6lJCNN8frgFoX_w5yPs">
> 
> Whole file is diagnosed with errors
> 
> any help?

If your new components have conflicting dependencies already installed you may get an error,
 --legacy-peer-deps is a temporary fix

**Comment by Abood2284** [comment]
@jasonjos111 this command doesn't seem to work on workspaces: `npm config set legacy-peer-deps true`
<img width="890" alt="Screenshot 2024-11-11 at 8 19 15 PM" src="https://github.com/user-attachments/assets/9676b188-b063-4a83-911a-4b033429b5ab">

this is what i get if i run this command inside my NextJs project inside a monorepo

well if i run this command: `npm config set legacy-peer-deps true`
in the root of my monorepo
<img width="843" alt="Screenshot 2024-11-11 at 8 20 18 PM" src="https://github.com/user-attachments/assets/4c6a1a32-d853-4cd2-93f4-7ffaafad39be">


i don't get any output- meaning it works.


But the error is still there:
<img width="844" alt="Screenshot 2024-11-11 at 8 20 45 PM" src="https://github.com/user-attachments/assets/213b271e-4e48-4cb3-88a6-1fd95c9002b2">

**Comment by Svendolin** [comment]
So it is definitely an issue with next.js Version 15.

I have taken the trouble to go back to the oldest Next version 14, to 14.2.14 to be precise.
Of course it's not really completely solved, but with this version I no longer have any error messages and can continue working with Shadcnui-

In my current repo I have described at the bottom under DEBUGGING and ERROR LOG how I went back to V14 and was able to continue working.: https://github.com/Svendolin/Bachelor-Project-SKA2025

I hope we can jump back to V15 at some point🤒

**Comment by marwanboudiab** [comment]
Error with Radix UI Menu: Module Not Found for @radix-ui/react-dismissable-layer

I’m encountering the following error when running pnpm run dev

⨯ ./node_modules/.pnpm/@radix-ui+react-menu@2.1.2_@types+react-dom@18.3.1_@types+react@18.3.12_react-dom@19.0.0-rc-0_o4jcdnyvzxbdzi7cnpkmx2wl2q/node_modules/@radix-ui/react-menu/dist/index.mjs:10:1
Module not found: Can't resolve '@radix-ui/react-dismissable-layer'
   8 | import { createContextScope } from "@radix-ui/react-context";
   9 | import { useDirection } from "@radix-ui/react-direction";
> 10 | import { DismissableLayer } from "@radix-ui/react-dismissable-layer";
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  11 | import { useFocusGuards } from "@radix-ui/react-focus-guards";
  12 | import { FocusScope } from "@radix-ui/react-focus-scope";
  13 | import { useId } from "@radix-ui/react-id";

https://nextjs.org/docs/messages/module-not-found

The error occurs during pnpm run dev, but pnpm run build works fine.

**Steps Taken**
Verified that packages are installed.
Attempted reinstalling dependencies with pnpm install.

**Environment**
Package manager: pnpm
React version: 19.0.0-rc-02c0e824-20241028
pnpm run build: Works
pnpm run dev: Error

**Any suggestions or fixes would be greatly appreciated!**

**Comment by MarwanBDdev** [comment]
Error with Radix UI Menu: Module Not Found for @radix-ui/react-dismissable-layer

I’m encountering the following error when running pnpm run dev

⨯ ./node_modules/.pnpm/https://github.com/radix-ui+react-menu@[2.1.2_@types](mailto:2.1.2_@types)+react-dom@[18.3.1_@types](mailto:18.3.1_@types)+react@[18.3.12_react-dom@19.0.0-rc-0_o4jcdnyvzxbdzi7cnpkmx2wl2q](mailto:18.3.12_react-dom@19.0.0-rc-0_o4jcdnyvzxbdzi7cnpkmx2wl2q)/node_modules/@radix-ui/react-menu/dist/index.mjs:10:1
Module not found: Can't resolve '@radix-ui/react-dismissable-layer'
8 | import { createContextScope } from "@radix-ui/react-context";
9 | import { useDirection } from "@radix-ui/react-direction";

10 | import { DismissableLayer } from "@radix-ui/react-dismissable-layer";
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11 | import { useFocusGuards } from "@radix-ui/react-focus-guards";
12 | import { FocusScope } from "@radix-ui/react-focus-scope";
13 | import { useId } from "@radix-ui/react-id";

https://nextjs.org/docs/messages/module-not-found

The error occurs during pnpm run dev, but pnpm run build works fine.

Steps Taken
Verified that packages are installed.
Attempted reinstalling dependencies with pnpm install.

Environment
Package manager: pnpm
React version: 19.0.0-rc-02c0e824-20241028

pnpm run build: Works
pnpm run dev: Error

Any suggestions or fixes would be greatly appreciated

**Comment by mengbo-ji** [comment]
> > 有人可以确认一下它是否有效吗`pnpm`？
> > `pnpm dlx shadcn@latest init`
> 
> 在我这边工作。

**Comment by fabioMacieira16** [comment]
run the command : npm install next@latest react@latest react-dom@latest

**Comment by Fearless09** [comment]
This fixed the error for me 
```
{
  "packageManager": "npm@10.5.2",
  "overrides": {
    "react": "$react",
    "react-dom": "$react-dom"
  },
  "dependencies": {
    "again": "^0.0.1",
    "next": "15.0.1",
    "next-auth": "^5.0.0-beta.25",
    "react": "19.0.0-rc-69d4b800-20241021",
    "react-dom": "19.0.0-rc-69d4b800-20241021"
  }
}
```

I found the solution on [here: https://github.com/vercel/next.js/issues/72204](https://github.com/vercel/next.js/issues/72204).

- **Note React version 19 has not been released officially**

**Comment by jacobsamo** [comment]
Getting the same issues as @jasonjos111,

> @jasonjos111 this command doesn't seem to work on workspaces: `npm config set legacy-peer-deps true` <img alt="Screenshot 2024-11-11 at 8 19 15 PM" width="890" src="https://private-user-images.githubusercontent.com/90205565/384964394-9676b188-b063-4a83-911a-4b033429b5ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0OTQzNDEsIm5iZiI6MTczMjQ5NDA0MSwicGF0aCI6Ii85MDIwNTU2NS8zODQ5NjQzOTQtOTY3NmIxODgtYjA2My00YTgzLTkxMWEtNGIwMzM0MjliNWFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDAwMjA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1MDM0MWE5YWI3YTcxYmQ3MTc2M2MyNmY3YWEyNWNiNjFmMWYwOTlhZGQyOWY4YjlhMmQ1NmE4NmEyMGYwNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.p5G4p5KigETLom9OTyd0-dUw3-Fc0pyxG-4pf2jU5L8">
> 
> this is what i get if i run this command inside my NextJs project inside a monorepo
> 
> well if i run this command: `npm config set legacy-peer-deps true` in the root of my monorepo <img alt="Screenshot 2024-11-11 at 8 20 18 PM" width="843" src="https://private-user-images.githubusercontent.com/90205565/384964723-4c6a1a32-d853-4cd2-93f4-7ffaafad39be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0OTQzNDEsIm5iZiI6MTczMjQ5NDA0MSwicGF0aCI6Ii85MDIwNTU2NS8zODQ5NjQ3MjMtNGM2YTFhMzItZDg1My00Y2QyLTkzZjQtN2ZmYWFmYWQzOWJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDAwMjA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkMTgwOWIzZWM5NTgwZTk4MWY5NDFlM2M0N2QxYjhjZDlhMTBmNWY0ZDg4ZjJlYzQwMzY1MWU4M2I2ZDFjNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Fc5vDAJSxcXZSb2WwtdaBiKqH74OUmwRDIuAtUo4uoo">
> 
> i don't get any output- meaning it works.
> 
> But the error is still there: <img alt="Screenshot 2024-11-11 at 8 20 45 PM" width="844" src="https://private-user-images.githubusercontent.com/90205565/384964876-213b271e-4e48-4cb3-88a6-1fd95c9002b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0OTQzNDEsIm5iZiI6MTczMjQ5NDA0MSwicGF0aCI6Ii85MDIwNTU2NS8zODQ5NjQ4NzYtMjEzYjI3MWUtNGU0OC00Y2IzLTg4YTYtMWZkOTVjOTAwMmIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDAwMjA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NDFiYjc2YTAzZWY5YjczMTlhMmNhZjQ4YzNlMDc2YjMyMGE2OWM4Mzg0YTU5YmI5ZDM1NzI5NGRmNTI0MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zaME-bGOCekuN_mmVefRn8QlaJ3IA6hr3ZQ8oqOO4ms">

## Setup:
- Package manager: bun v1.1.36
- system i am expericing the issue on: MacOS 14.5 & Window 11
- React version: react@19.0.0-rc.1, react-dom@19.0.0-rc.1


### Errors:
What is see in my UI components:
```bash
Type 'ForwardRefExoticComponent<AccordionItemProps & RefAttributes<HTMLDivElement>>' does not satisfy the constraint 'keyof IntrinsicElements | ForwardRefExoticComponent<any> | (new (props: any) => Component<any, {}, any>) | ((props: any) => ReactNode)'.
  Type 'ForwardRefExoticComponent<AccordionItemProps & RefAttributes<HTMLDivElement>>' is not assignable to type 'ForwardRefExoticComponent<any>'.
    Type 'React.ReactNode' is not assignable to type 'import("/Users/jacob/Documents/GitHub/BuzzTrip/apps/web/node_modules/@types/react/index").ReactNode'.
      Type 'bigint' is not assignable to type 'ReactNode'.
```

what is see when consuming my components:
```bash
'Button' cannot be used as a JSX component.
  Its type 'ForwardRefExoticComponent<ButtonProps & RefAttributes<HTMLButtonElement>>' is not a valid JSX element type.
    Type 'ForwardRefExoticComponent<ButtonProps & RefAttributes<HTMLButtonElement>>' is not assignable to type '(props: any, deprecatedLegacyContext?: any) => ReactNode'.
      Type 'import("/Users/jacob/Documents/GitHub/BuzzTrip/apps/web/node_modules/@types/react/index").ReactNode' is not assignable to type 'React.ReactNode'.
        Type 'ReactElement<unknown, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode'.
          Property 'children' is missing in type 'ReactElement<unknown, string | JSXElementConstructor<any>>' but required in type 'ReactPortal'.
```

Not sure how to fix this issue, i have tried setting `npm config set legacy-peer-deps true` didn't fix anything.

The repo: [https://github.com/jacobsamo/BuzzTrip/tree/improve-web](https://github.com/jacobsamo/BuzzTrip/tree/improve-web)

**Comment by zipme** [comment]
> Getting the same issues as @jasonjos111,
> 
> > @jasonjos111 this command doesn't seem to work on workspaces: `npm config set legacy-peer-deps true` <img alt="Screenshot 2024-11-11 at 8 19 15 PM" width="890" src="https://private-user-images.githubusercontent.com/90205565/384964394-9676b188-b063-4a83-911a-4b033429b5ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0OTQzNDEsIm5iZiI6MTczMjQ5NDA0MSwicGF0aCI6Ii85MDIwNTU2NS8zODQ5NjQzOTQtOTY3NmIxODgtYjA2My00YTgzLTkxMWEtNGIwMzM0MjliNWFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDAwMjA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1MDM0MWE5YWI3YTcxYmQ3MTc2M2MyNmY3YWEyNWNiNjFmMWYwOTlhZGQyOWY4YjlhMmQ1NmE4NmEyMGYwNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.p5G4p5KigETLom9OTyd0-dUw3-Fc0pyxG-4pf2jU5L8">
> > this is what i get if i run this command inside my NextJs project inside a monorepo
> > well if i run this command: `npm config set legacy-peer-deps true` in the root of my monorepo <img alt="Screenshot 2024-11-11 at 8 20 18 PM" width="843" src="https://private-user-images.githubusercontent.com/90205565/384964723-4c6a1a32-d853-4cd2-93f4-7ffaafad39be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0OTQzNDEsIm5iZiI6MTczMjQ5NDA0MSwicGF0aCI6Ii85MDIwNTU2NS8zODQ5NjQ3MjMtNGM2YTFhMzItZDg1My00Y2QyLTkzZjQtN2ZmYWFmYWQzOWJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDAwMjA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkMTgwOWIzZWM5NTgwZTk4MWY5NDFlM2M0N2QxYjhjZDlhMTBmNWY0ZDg4ZjJlYzQwMzY1MWU4M2I2ZDFjNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Fc5vDAJSxcXZSb2WwtdaBiKqH74OUmwRDIuAtUo4uoo">
> > i don't get any output- meaning it works.
> > But the error is still there: <img alt="Screenshot 2024-11-11 at 8 20 45 PM" width="844" src="https://private-user-images.githubusercontent.com/90205565/384964876-213b271e-4e48-4cb3-88a6-1fd95c9002b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0OTQzNDEsIm5iZiI6MTczMjQ5NDA0MSwicGF0aCI6Ii85MDIwNTU2NS8zODQ5NjQ4NzYtMjEzYjI3MWUtNGU0OC00Y2IzLTg4YTYtMWZkOTVjOTAwMmIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDAwMjA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NDFiYjc2YTAzZWY5YjczMTlhMmNhZjQ4YzNlMDc2YjMyMGE2OWM4Mzg0YTU5YmI5ZDM1NzI5NGRmNTI0MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zaME-bGOCekuN_mmVefRn8QlaJ3IA6hr3ZQ8oqOO4ms">
> 
> ## Setup:
> * Package manager: bun v1.1.36
> * system i am expericing the issue on: MacOS 14.5 & Window 11
> * React version: react@19.0.0-rc.1, react-dom@19.0.0-rc.1
> 
> ### Errors:
> What is see in my UI components:
> 
> ```shell
> Type 'ForwardRefExoticComponent<AccordionItemProps & RefAttributes<HTMLDivElement>>' does not satisfy the constraint 'keyof IntrinsicElements | ForwardRefExoticComponent<any> | (new (props: any) => Component<any, {}, any>) | ((props: any) => ReactNode)'.
>   Type 'ForwardRefExoticComponent<AccordionItemProps & RefAttributes<HTMLDivElement>>' is not assignable to type 'ForwardRefExoticComponent<any>'.
>     Type 'React.ReactNode' is not assignable to type 'import("/Users/jacob/Documents/GitHub/BuzzTrip/apps/web/node_modules/@types/react/index").ReactNode'.
>       Type 'bigint' is not assignable to type 'ReactNode'.
> ```
> 
> what is see when consuming my components:
> 
> ```shell
> 'Button' cannot be used as a JSX component.
>   Its type 'ForwardRefExoticComponent<ButtonProps & RefAttributes<HTMLButtonElement>>' is not a valid JSX element type.
>     Type 'ForwardRefExoticComponent<ButtonProps & RefAttributes<HTMLButtonElement>>' is not assignable to type '(props: any, deprecatedLegacyContext?: any) => ReactNode'.
>       Type 'import("/Users/jacob/Documents/GitHub/BuzzTrip/apps/web/node_modules/@types/react/index").ReactNode' is not assignable to type 'React.ReactNode'.
>         Type 'ReactElement<unknown, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode'.
>           Property 'children' is missing in type 'ReactElement<unknown, string | JSXElementConstructor<any>>' but required in type 'ReactPortal'.
> ```
> 
> Not sure how to fix this issue, i have tried setting `npm config set legacy-peer-deps true` didn't fix anything.
> 
> The repo: https://github.com/jacobsamo/BuzzTrip/tree/improve-web

Try this: In https://github.com/jacobsamo/BuzzTrip/blob/improve-web/package.json add the following:
```json
 "overrides": {
    "@types/react": "npm:types-react@19.0.0-rc.1",
    "@types/react-dom": "npm:types-react-dom@19.0.0-rc.1"
  }
```
Then delete all the node_modules and re-run `bun i`

**Comment by 2Senn** [comment]
Anyone know how to fix the error 'button cannot be used as a JSX component' in a turborepo? I have to add pnpm overrides in the root workspace but that is also giving me an error

**Comment by CryptoNinja0331** [comment]
> npm config set legacy-peer-deps true

This works very well

**Comment by aifirstd3v** [comment]
if you use `bun`, add this

```json
"overrides": {
    "react-is": "$react-is",
    "@types/react": "npm:types-react@19.0.0-rc.1",
    "@types/react-dom": "$@types/react-dom-rc.1"
  },
"resolutions": {
    "@types/react": "npm:types-react@19.0.0-rc.1",
    "@types/react-dom": "npm:types-react-dom@19.0.0-rc.1"
  }
```

**Comment by candle-admin** [comment]
I also see this issue.

**Comment by stevenlei** [comment]
Could be a temporary solution, this works for me:

`npm install date-fns --legacy-peer-deps`

**Comment by avijit-shihaan** [comment]
Nextjs got updated with react stable , why are still getting the ```force``` or ```legacy deps``` warning?

**Comment by hamidradical** [comment]
Any update regarding nextjs15 and other one more library that creates problem for installation:- Radix?

**Comment by palmithor** [comment]
I have a problem related to this. I'm using `bun` and bun workspaces & react 19. When I do 
`bunx --bun shadcn@latest init -c ./apps/frontend` it prompts me due to legacy peer deps (I actually don't have any).
```
? How would you like to proceed? › - Use arrow-keys. Return to submit.
❯   Use --force
    Use --legacy-peer-deps
```

However, this fails because it tries to run `npm i` instead of `bun i`

```
Something went wrong. Please check the error below for more details.
If the problem persists, please open an issue on GitHub.

Command failed with exit code 1: npm install --force tailwindcss-animate class-variance-authority lucide-react clsx tailwind-merge
npm warn using --force Recommended protections disabled.
npm error code EUNSUPPORTEDPROTOCOL
npm error Unsupported URL Type "workspace:": workspace:*
```

**Comment by Andrew-Chen-Wang** [comment]
What is actually required for ShadCN to support React 19? I'll start a list:

- [ ] https://github.com/shadcn-ui/ui/pull/4356
- [ ] https://github.com/shadcn-ui/ui/pull/6262

**Comment by Danfraga33** [comment]
Problem with calendar still persists. 

![image](https://github.com/user-attachments/assets/a898979f-5603-4668-93b9-050ac34700a2)

Any solutions ?

**Comment by Michael-Liendo** [comment]
Same here!

**Comment by souvik-basak** [comment]
I think one thing that can be done is to use `--legacy-peer-deps`

try to run in the command prompt
`npm install shadcn --legacy-peer-deps`

I am unsure about this command, please let me know if it works.

**Comment by arashmad** [comment]
Maybe my experience helps some of you, if you have similar issue in running pipeline using command `npm ci`.
Recently I tried to establish CI using action `actions/setup-node@v4` with following configuration:
```
name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
```

and got pipeline failed as follow:
```
...
Run npm ci
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: cmdk@1.0.0
npm error Found: react@19.0.0
npm error node_modules/react
npm error   react@"^19.0.0" from the root project
npm error   peer react@">=16.8.0" from @floating-ui/react-dom@2.1.2
npm error   node_modules/@floating-ui/react-dom
npm error     @floating-ui/react-dom@"^2.0.0" from @radix-ui/react-popper@1.2.1
npm error     node_modules/@radix-ui/react-popper
npm error       @radix-ui/react-popper@"1.2.1" from @radix-ui/react-popover@1.1.[4](https://github.com/arashmad/web-map-application/actions/runs/12986620663/job/36213824091#step:4:5)
npm error       node_modules/@radix-ui/react-popover
npm error         @radix-ui/react-popover@"^1.1.4" from the root project
npm error   33 more (@radix-ui/react-arrow, @radix-ui/react-compose-refs, ...)
npm error
npm error Could not resolve dependency:
npm error peer react@"^18.0.0" from cmdk@1.0.0
npm error node_modules/cmdk
npm error   cmdk@"^1.0.0" from the root project
npm error
npm error Conflicting peer dependency: react@18.3.1
npm error node_modules/react
npm error   peer react@"^18.0.0" from cmdk@1.0.0
npm error   node_modules/cmdk
npm error     cmdk@"^1.0.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /home/runner/.npm/_logs/202[5](https://github.com/arashmad/web-map-application/actions/runs/12986620663/job/36213824091#step:4:6)-01-27T10_11_15_387Z-eresolve-report.txt
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2025-01-2[7](https://github.com/arashmad/web-map-application/actions/runs/12986620663/job/36213824091#step:4:8)T10_11_15_387Z-debug-0.log
Error: Process completed with exit code 1.
...
```
Searching a bit on google, I came across [this post](https://stackoverflow.com/questions/52499617/what-is-the-difference-between-npm-install-and-npm-ci).
Then on my local project, I removed the package-lock.json file and and also node_modules directory and execute `npm i` again to fix issue in version mismatch as `npm ci` is sensitive and breaks pipeline.

**Comment by Michael-Liendo** [comment]
It happened to me when I wanted to use the [Date Picker](https://ui.shadcn.com/docs/components/date-picker#installation) component, I don't remember well, but what I remember is that I installed `date-fns` using `npm install date-fns`, and that gave me an error, I fixed it by doing this: uninstalling it, and then running `npx shadcn@latest add calendar` and that installed the correct version of `date-fns`.

**Comment by nephix** [comment]
> Getting the same issues as [@jasonjos111](https://github.com/jasonjos111),
> 
> > [@jasonjos111](https://github.com/jasonjos111) this command doesn't seem to work on workspaces: `npm config set legacy-peer-deps true` <img alt="Screenshot 2024-11-11 at 8 19 15 PM" width="890" src="https://private-user-images.githubusercontent.com/90205565/384964394-9676b188-b063-4a83-911a-4b033429b5ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0OTQzNDEsIm5iZiI6MTczMjQ5NDA0MSwicGF0aCI6Ii85MDIwNTU2NS8zODQ5NjQzOTQtOTY3NmIxODgtYjA2My00YTgzLTkxMWEtNGIwMzM0MjliNWFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDAwMjA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1MDM0MWE5YWI3YTcxYmQ3MTc2M2MyNmY3YWEyNWNiNjFmMWYwOTlhZGQyOWY4YjlhMmQ1NmE4NmEyMGYwNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.p5G4p5KigETLom9OTyd0-dUw3-Fc0pyxG-4pf2jU5L8">
> > this is what i get if i run this command inside my NextJs project inside a monorepo
> > well if i run this command: `npm config set legacy-peer-deps true` in the root of my monorepo <img alt="Screenshot 2024-11-11 at 8 20 18 PM" width="843" src="https://private-user-images.githubusercontent.com/90205565/384964723-4c6a1a32-d853-4cd2-93f4-7ffaafad39be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0OTQzNDEsIm5iZiI6MTczMjQ5NDA0MSwicGF0aCI6Ii85MDIwNTU2NS8zODQ5NjQ3MjMtNGM2YTFhMzItZDg1My00Y2QyLTkzZjQtN2ZmYWFmYWQzOWJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDAwMjA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkMTgwOWIzZWM5NTgwZTk4MWY5NDFlM2M0N2QxYjhjZDlhMTBmNWY0ZDg4ZjJlYzQwMzY1MWU4M2I2ZDFjNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Fc5vDAJSxcXZSb2WwtdaBiKqH74OUmwRDIuAtUo4uoo">
> > i don't get any output- meaning it works.
> > But the error is still there: <img alt="Screenshot 2024-11-11 at 8 20 45 PM" width="844" src="https://private-user-images.githubusercontent.com/90205565/384964876-213b271e-4e48-4cb3-88a6-1fd95c9002b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0OTQzNDEsIm5iZiI6MTczMjQ5NDA0MSwicGF0aCI6Ii85MDIwNTU2NS8zODQ5NjQ4NzYtMjEzYjI3MWUtNGU0OC00Y2IzLTg4YTYtMWZkOTVjOTAwMmIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDAwMjA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NDFiYjc2YTAzZWY5YjczMTlhMmNhZjQ4YzNlMDc2YjMyMGE2OWM4Mzg0YTU5YmI5ZDM1NzI5NGRmNTI0MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zaME-bGOCekuN_mmVefRn8QlaJ3IA6hr3ZQ8oqOO4ms">
> 
> ## Setup:
> * Package manager: bun v1.1.36
> * system i am expericing the issue on: MacOS 14.5 & Window 11
> * React version: react@19.0.0-rc.1, react-dom@19.0.0-rc.1
> 
> ### Errors:
> What is see in my UI components:
> 
> Type 'ForwardRefExoticComponent<AccordionItemProps & RefAttributes<HTMLDivElement>>' does not satisfy the constraint 'keyof IntrinsicElements | ForwardRefExoticComponent<any> | (new (props: any) => Component<any, {}, any>) | ((props: any) => ReactNode)'.
>   Type 'ForwardRefExoticComponent<AccordionItemProps & RefAttributes<HTMLDivElement>>' is not assignable to type 'ForwardRefExoticComponent<any>'.
>     Type 'React.ReactNode' is not assignable to type 'import("/Users/jacob/Documents/GitHub/BuzzTrip/apps/web/node_modules/@types/react/index").ReactNode'.
>       Type 'bigint' is not assignable to type 'ReactNode'.
> what is see when consuming my components:
> 
> 'Button' cannot be used as a JSX component.
>   Its type 'ForwardRefExoticComponent<ButtonProps & RefAttributes<HTMLButtonElement>>' is not a valid JSX element type.
>     Type 'ForwardRefExoticComponent<ButtonProps & RefAttributes<HTMLButtonElement>>' is not assignable to type '(props: any, deprecatedLegacyContext?: any) => ReactNode'.
>       Type 'import("/Users/jacob/Documents/GitHub/BuzzTrip/apps/web/node_modules/@types/react/index").ReactNode' is not assignable to type 'React.ReactNode'.
>         Type 'ReactElement<unknown, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode'.
>           Property 'children' is missing in type 'ReactElement<unknown, string | JSXElementConstructor<any>>' but required in type 'ReactPortal'.
> Not sure how to fix this issue, i have tried setting `npm config set legacy-peer-deps true` didn't fix anything.
> 
> The repo: https://github.com/jacobsamo/BuzzTrip/tree/improve-web

I'm still running into this issue

```
bun v1.2.3-canary.29
react@^18.3.1
@types/react@18.3.3
```

```
Type 'ForwardRefExoticComponent<SlotProps & RefAttributes<HTMLElement>>' does not satisfy the constraint 'keyof IntrinsicElements | ForwardRefExoticComponent<any> | (new (props: any) => Component<any, {}, any>) | ((props: any, deprecatedLegacyContext?: any) => ReactNode)'.
  Type 'ForwardRefExoticComponent<SlotProps & RefAttributes<HTMLElement>>' is not assignable to type 'ForwardRefExoticComponent<any>'.
    Type 'React.ReactNode' is not assignable to type 'import(".../node_modules/@types/react/index").ReactNode'.
      Type 'bigint' is not assignable to type 'ReactNode'.
```

and when using `<FormControl>`:

```
Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes & RefAttributes<never>'.
```

**Comment by kurorinto** [comment]
Is this bug resolved now? I am so cold, because my boss asked me to blow cold air until it can be solved

**Comment by aca1490** [comment]
@kurorinto Solution for me was: 

npm install react@18.2.0 react-dom@18.2.0

**Comment by L3on06** [comment]
**Hi,** 

I had this issue after upgrading to React 19 and Tailwind CSS v4. However, I believe it will also work with just React 19. 

I encountered some other problems, but for the calendar specifically, 
the solution is to reinstall it by running:

### `npx shadcn@latest add calendar`

_Then, press 'Y' when prompted to overwrite._

Hope this will help :)

**Comment by shadcn** [comment]
Yes. This is fixed in the latest release. Please give it a try and let me know.

**Comment by L3on06** [comment]
> Yes. This is fixed in the latest release. Please give it a try and let me know.


Hi ShadCN, hope you're doing well.

I tried updating the calendar again, and while it did fix the issue, it didn’t work as expected.

The problem occurs when running:

**`npx shadcn@latest add calendar`**

 it downgrades react-day-picker to version ^8.10.1. As a result, when I deploy the project to Vercel in my case

I'm encountering an error because the date-fns and react-day-picker versions aren't compatible.

I've fixed the issue in my code. If you're open to it, I can create a pull request with my updates, and you can review and merge it.

Thanks for your time!

Best regards,
Leon

**Comment by shadcn** [comment]
@L3on06 oh sorry. I was replying to the original post about `init` failing. The calendar work is still in progress. Once Tailwind v4 support is out, I'll wrap up the calendar upgrade and push.

**Comment by pareshjinger** [comment]
How much time it gonna take?

> [@L3on06](https://github.com/L3on06) oh sorry. I was replying to the original post about `init` failing. The calendar work is still in progress. Once Tailwind v4 support is out, I'll wrap up the calendar upgrade and push.

**Comment by Anurag-Mishra22** [comment]
@shadcn 
any update on calendar work , still getting the error
The problem occurs when running:

npx shadcn@latest add calendar

it downgrades react-day-picker to version ^8.10.1. As a result, when I deploy the project to Vercel in my case

I'm encountering an error because the date-fns and react-day-picker versions aren't compatible.

**Comment by muneeb-i-khan** [comment]
It works with yarn as well for me.

**Comment by gunslingor** [comment]
Yikes... you guys should fix this, my first dive into using ShadCN ended in a brick wall here... the proposed workarounds are way to dangerous, one must assume they will result in dependency conflict or become permanent if its been this way for 6 months already.

**Comment by emnanwork** [comment]
same problem here

**Comment by vishal2457** [comment]
any updates on this issue, facing this with pnpm 9.7.0

pnpm dlx shadcn@latest add

Something went wrong. Please check the error below for more details.
If the problem persists, please open an issue on GitHub.

request to https://ui.shadcn.com/r/index.json failed, reason: read ECONNRESET

**Comment by shadcn** [comment]
Calendar is now on React 19. Closing this as done. Please open a new thread if you see any issue. Thank you.

**Comment by kidus1001** [comment]
Facing this issue as of 2026!!!

**Comment by deaduchiha** [comment]
just remove `package-lock.json` or `bun.lock`
