### ISSUE TITLE
[bug]: V4 Demo has some horizontal scroll on md screen

### ISSUE THREAD

**Issue by adiramardiani** [shadcn-ui/ui#6795]
### Describe the bug

Hi @shadcn 
Before this, to be honest the current block of sidebar has some vertical or horizontal issue when have 'real' content, not just 3 column and 1 column skeleton
I'm happy because on v4 demo this issue is not show like on sidebar block implementation
If I not wrong, yesterday the issue is not show, but today the issue is happening

On v4 demo https://v4.shadcn.com, when on specific medium screen, the content seems not wrapping, the width still full who cause annoying horizontal behavious, I notice for my datatable content on sidebar 07 layout, when I check on demo the issue is the same

I dont know this happen on my browser (edge), or another browser
I hope with @graphity catch on https://github.com/shadcn-ui/ui/issues/6651 will fixed this, but the v4 demo issue just let you know

https://github.com/user-attachments/assets/2ef1da36-7b40-4620-830f-dc3e17c130b2

![Image](https://github.com/user-attachments/assets/f9fec9ac-ef48-409b-9c16-353f644b826b)

And maybe this out of context, but on mobile (android) I cannot trigger the sidebar, on desktop browser I think the sidebar is show when I resize to smaller screen

Thanks

### Affected component/components

Sidebar

### How to reproduce

1. On browser (me is edge browser)
2. Try to resize screen to medium screen
3. Check the content is not wrapped properly, the horizontal is show, and content not wrapped

### Logs

```bash

```

### System Info

```bash
OS : Windows 11
Browser : Microsoft Edge
```

### Before submitting

- [x] I've made research efforts and searched the documentation
- [x] I've searched for existing issues

**Comment by huqedgar** [comment]
it isn't bug, just add "overflow-hidden" to **<SidebarInset className="overflow-hidden">** then the horizontal scroll bar will be inherited by the nearest child elements

**Comment by vnxpixel** [comment]
> ![Image](https://github.com/user-attachments/assets/daba9f3d-fdda-4951-943c-d015e370e9b6) it isn't bug, just add "overflow-hidden" to **SidebarInset**. Because the parent element has overflow-hidden, and when setting the child element to overflow, you can scroll the content inside the child element if the child element's width exceeds the parent element's width.

Just a note, having to use `overflow-hidden` at such a high level will prevent any `sticky` element inside it from working. Using `overflow-clip` as an alternative is better (browser support is not bad now) if you have `sticky` elements.

**Comment by Jacksonmills** [comment]
@shadcn Assign this to me. I refactored and fixed a few elements in the kitchen sink and resolved all horizontal scroll issues by addressing the button rows and calendar sections.

**Comment by huqedgar** [comment]
> > ![Image](https://github.com/user-attachments/assets/daba9f3d-fdda-4951-943c-d015e370e9b6) it isn't bug, just add "overflow-hidden" to **SidebarInset**. Because the parent element has overflow-hidden, and when setting the child element to overflow, you can scroll the content inside the child element if the child element's width exceeds the parent element's width.
> 
> Just a note, having to use `overflow-hidden` at such a high level will prevent any `sticky` element inside it from working. If you want to solve it by modifying overflow on `SidebarInset`, using `overflow-clip` as an alternative is better (browser support is not bad now) if you have `sticky` elements.



> [@shadcn](https://github.com/shadcn) Assign this to me. I refactored and fixed a few elements in the kitchen sink and resolved all horizontal scroll issues by addressing the button rows and calendar sections. afaik this bug has nothing to do with the sidebar itself.

![Image](https://github.com/user-attachments/assets/c1b6c5b7-8ec9-47a6-a436-f2e234692dd7)


I think the issue is not related to addressing the button rows and calendar sections because I have implemented Sidebar 07 as shown in the image, where "<Outlet />" is a table with many columns and a horizontal scroll bar. I encountered the same issue as @adiramardiani :  
- I tried using "overflow-clip" as mentioned by @vnxpixel , but it had no effect. The same goes for "<SidebarProvider />". Instead, I used "overflow-hidden" for "<SidebarInset />".  
- I am not using any "<Button />" or "<Calendar />" components inside "<Outlet />"; I am only using "<Table />". So, I’m wondering if the issue @Jacksonmills mentioned is actually a different one.

**Comment by huqedgar** [comment]
> > > > ![Image](https://github.com/user-attachments/assets/daba9f3d-fdda-4951-943c-d015e370e9b6) it isn't bug, just add "overflow-hidden" to **SidebarInset**. Because the parent element has overflow-hidden, and when setting the child element to overflow, you can scroll the content inside the child element if the child element's width exceeds the parent element's width.
> > > 
> > > 
> > > Just a note, having to use `overflow-hidden` at such a high level will prevent any `sticky` element inside it from working. If you want to solve it by modifying overflow on `SidebarInset`, using `overflow-clip` as an alternative is better (browser support is not bad now) if you have `sticky` elements.
> > 
> > 
> > > [@shadcn](https://github.com/shadcn) Assign this to me. I refactored and fixed a few elements in the kitchen sink and resolved all horizontal scroll issues by addressing the button rows and calendar sections. afaik this bug has nothing to do with the sidebar itself.
> > 
> > 
> > ![Image](https://github.com/user-attachments/assets/c1b6c5b7-8ec9-47a6-a436-f2e234692dd7)
> > I think the issue is not related to addressing the button rows and calendar sections because I have implemented Sidebar 07 as shown in the image, where "Outlet" is a table with many columns and a horizontal scroll bar. I encountered the same issue as [@adiramardiani](https://github.com/adiramardiani) :
> > 
> > * I tried using "overflow-clip" as mentioned by [@vnxpixel](https://github.com/vnxpixel) , but it had no effect. The same goes for "SidebarProvider". Instead, I used "overflow-hidden" for "SidebarInset".
> > * I am not using any "Button" or "Calendar" components inside "Outlet"; I am only using "Table". So, I’m wondering if the issue [@Jacksonmills](https://github.com/Jacksonmills) mentioned is actually a different one.
> 
> I just tried `overflow-clip` as well, and it didn't work like you said. Might have to look more into it. I really don't like `overflow-hidden` as a solution for this since it prevents you using `sticky` elements in your main content, which feels more like a band-aid sadly.
> 
> The fixes that [@Jacksonmills](https://github.com/Jacksonmills) made is only for the v4 page. The horizontal scrolling happens when the content is wider than the width of the page. This is unavoidable in some cases - tables with many columns for example.
> 
> There is an old issue about this actually which is good reference. It was closed without a proper resolution. [Issue 5545](https://github.com/shadcn-ui/ui/issues/5545)

I agree with you, these issues are minor bugs. We can either wait for a better solution or restructure the entire layout, and the problem will be resolved.

**Comment by shadcn** [comment]
@Jacksonmills I noticed this bug as well yesterday and pushed a fix for it. Let me check if this is still happening.

**Comment by adiramardiani** [comment]
Hi @shadcn @Jacksonmills 
I try out your updated v4 demo and I can confirm this issue has been fixed, I think this issue can be closed :)

Thank you so much

**Comment by RowinVanAmsterdam** [comment]
> [@Jacksonmills](https://github.com/Jacksonmills) I noticed this bug as well yesterday and pushed a fix for it. Let me check if this is still happening.

Just upgraded to tailwind v4 and re-installed sidebar with shadcn cli 2.4. I notice the issue is still there. Did I miss a step?

**Comment by andreivictor** [comment]
I've used `<SidebarInset className="min-w-0" />` and it resolved the layout issue for me.
This approach doesn’t break any sticky elements inside, unlike setting `overflow-hidden`, which can interfere with sticky positioning.

**Comment by jcalzolari** [comment]
> > [@Jacksonmills](https://github.com/Jacksonmills) I noticed this bug as well yesterday and pushed a fix for it. Let me check if this is still happening.
> 
> Just upgraded to tailwind v4 and re-installed sidebar with shadcn cli 2.4. I notice the issue is still there. Did I miss a step?

Issue still here as of today; `<SidebarInset className="overflow-hidden">` does fix it but losing sticky styling is a bummer :(

**Comment by boningmaple** [comment]
> > > [@Jacksonmills](https://github.com/Jacksonmills) I noticed this bug as well yesterday and pushed a fix for it. Let me check if this is still happening.
> > 
> > 
> > Just upgraded to tailwind v4 and re-installed sidebar with shadcn cli 2.4. I notice the issue is still there. Did I miss a step?
> 
> Issue still here as of today; `<SidebarInset className="overflow-hidden">` does fix it but losing sticky styling is a bummer :(

~~Same here, add `overflow-hidden` fix the problem but my sticky header is not working.~~
Just find a solution here: https://github.com/shadcn-ui/ui/issues/5545#issuecomment-2867696778

Thanks @andreivictor
