### ISSUE TITLE
[bug]: npx shadcn@latest init not working

### ISSUE THREAD

**Issue by junleyan** [shadcn-ui/ui#8552]
### Describe the bug

I'm stuck on "Creating a New Next.js project" after running `npx shadcn@latest init`. I’ve waited about 10 minutes, but it’s still stuck, the /app directory hasn't even been created after all the waits.
```
(base) username@MacBook-Air-3 repo_name % npx shadcn@latest init
✔ The path /Users/username/Downloads/repo_name does not contain a package.json file.
  Would you like to start a new project? › Next.js
✔ What is your project named? … app
⠸ Creating a new Next.js project. This may take a few minutes.
```

### Affected component/components

N/A

### How to reproduce

1. Run npx shadcn@latest init.
2. Select "Next.js" when prompted with "Would you like to start a new project?"
3. Enter any name when asked "What is your project named?"
4. You'll now be stuck at "Creating a new Next.js project. This may take a few minutes."

### Logs

```bash

```

### System Info

```bash
System: macOS 14.6 (Sonoma), Build 23G80
Hardware: MacBook Air (M2, Model Identifier Mac14,2) with 8 GB RAM
Architecture: ARM64 (Apple Silicon)
CPU: 8 cores (4 performance + 4 efficiency)
Kernel: Darwin 23.6.0
```

### Before submitting

- [x] I've made research efforts and searched the documentation
- [x] I've searched for existing issues

**Comment by cfassoni** [comment]
I've got same issue on Windows.
Then I tried to create the next.js project prior to initialize shadcn and it worked.
Here are the steps:
```
npx create-next-app@latest my-app --yes
cd my-app
npm run dev (optional, just to check)
npx shadcn@latest init
npx shadcn@latest add button
```

**Comment by junleyan** [comment]
> I've got same issue on Windows. Then I tried to create the next.js project prior to initialize shadcn and it worked. Here are the steps:
> 
> ```
> npx create-next-app@latest my-app --yes
> cd my-app
> npm run dev (optional, just to check)
> npx shadcn@latest init
> npx shadcn@latest add button
> ```

I got it to work this way too, but is it a common issue for `npx shadcn@latest init` to not work?

**Comment by andymcbee** [comment]
Ran into this also.

**Comment by andymcbee** [comment]
I sorted this out on my end.

I tried a few things, but it looks like I was on React 19, and that was causing issues with some of the shadcn deps. 

I downgraded react to 18, then went through the manual install instructions and it worked the first time through.

I also deleted my .next dir and node modules and re-installed them before doing the manual instructions. https://ui.shadcn.com/docs/installation/manual

**Comment by shadcn** [comment]
I believe this was an issue with `create-next-app` for Next.js 16. Should be solved now. If not, try `npx clear-npx-cache` then run `npx shadcn@latest init` again.

**Comment by jonathanpv** [comment]
interesting i run into init issues as well

```bash
jon@mac ⚡️ npx clear-npx-cache
Need to install the following packages:
clear-npx-cache@1.1.2
Ok to proceed? (y) y

 Starting cleaning ... 

 ████████████████████████████████████████ 100% | ETA: 0s | 21/21

 Cache cleared successfully! Thanks for using our lib.
jon@mac ⚡️ npx shadcn@latest init
Need to install the following packages:
shadcn@3.5.0
Ok to proceed? (y) y

npm warn deprecated node-domexception@1.0.0: Use your platform's native DOMException instead
✔ The path /Users/jon/coding-project does not contain a package.json file.
  Would you like to start a new project? › Next.js 15
✔ What is your project named? … YourApplicant
⠴ Creating a new Next.js 15 project. This may take a few minutes.
Something went wrong creating a new Next.js project. Please try again.
jon@mac ⚡️ 
```

**Comment by jonathanpv** [comment]
going to try to restart computer and see if it fixes itself

```
jon@mac ⚡️ pnpm dlx shadcn@latest init --template next
✔ What is your project named? … YourApplicant
⠴ Creating a new Next.js 15 project. This may take a few minutes.
Something went wrong creating a new Next.js project. Please try again.
jon@mac ⚡️ 

```

**Comment by jonathanpv** [comment]
still not working not pnpm dlx either going to try earlier version maybe thatll do 

```
Progress: resolved 319, reused 318, downloaded 1, added 319, done
3.5.0
jon@mac ⚡️ pnpm dlx shadcn@3.5.1-canary.0 init     
✔ The path /Users/jon/coding-project does not contain a package.json file.
  Would you like to start a new project? › Next.js 15
✔ What is your project named? … YourApplicant
⠋ Creating a new Next.js 15 project. This may take a few minutes.
Something went wrong creating a new Next.js project. Please try again.
jon@mac ⚡️ 
```

```
jon@mac ⚡️ pnpm dlx shadcn@3.4.2 init         
 WARN  1 deprecated subdependencies found: node-domexception@1.0.0
Packages: +319
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 319, reused 319, downloaded 0, added 319, done
✔ The path /Users/jon/coding-project does not contain a package.json file.
  Would you like to start a new project? › Next.js
✔ What is your project named? … YourApplicant
⠦ Creating a new Next.js project. This may take a few minutes.
Something went wrong creating a new Next.js project. Please try again.
jon@mac ⚡️ 
```

i suspected it may be to a full harddrive but not it because i have 93GB used out of 245GB

ill try in a new folder maybe thats why


```
jon@mac ⚡️ pnpm dlx shadcn@3.4.2 init
✔ The path /Users/jon/coding-project-2 does not contain a package.json file.
  Would you like to start a new project? › Next.js
✔ What is your project named? … YourApplicant
⠙ Creating a new Next.js project. This may take a few minutes.
Something went wrong creating a new Next.js project. Please try again.
jon@mac ⚡️ 



```

nope 

idk what else to try ? maybe continue older ones

**Comment by jonathanpv** [comment]
running pnpm store prune
```
jon@mac ⚡️ pnpm store prune
Removed all cached metadata files
Removed 272073 files
Removed 5260 packages
jon@mac ⚡️ pnpm store prune --force
 WARN  using --force I sure hope you know what you are doing
Removed all cached metadata files
Removed 0 files
Removed 0 packages
jon@mac ⚡️ pnpm dlx shadcn@latest init --verbose
error: unknown option '--verbose'
jon@mac ⚡️ pnpm dlx shadcn@latest init          
✔ The path /Users/jon/coding-project-2 does not contain a package.json file.
  Would you like to start a new project? › Next.js 15
✔ What is your project named? … YourApplicant
⠹ Creating a new Next.js 15 project. This may take a few minutes.
Something went wrong creating a new Next.js project. Please try again.
jon@mac ⚡️ 

```

some system info:
```
jon@mac ⚡️ pnpm --version
9.15.4
jon@mac ⚡️ node --version
v22.12.0
jon@mac ⚡️ pnpm store path
/Users/jon/Library/pnpm/store/v3
jon@mac ⚡️ df -h
Filesystem        Size    Used   Avail Capacity iused ifree %iused  Mounted on
/dev/disk3s1s1   228Gi    10Gi    67Gi    14%    412k  704M    0%   /
devfs            199Ki   199Ki     0Bi   100%     690     0  100%   /dev
/dev/disk3s6     228Gi    24Ki    67Gi     1%       0  704M    0%   /System/Volumes/VM
/dev/disk3s2     228Gi   7.3Gi    67Gi    10%    1.7k  704M    0%   /System/Volumes/Preboot
/dev/disk3s4     228Gi   3.0Mi    67Gi     1%      59  704M    0%   /System/Volumes/Update
/dev/disk1s2     500Mi   6.0Mi   483Mi     2%       3  4.9M    0%   /System/Volumes/xarts
/dev/disk1s1     500Mi   5.4Mi   483Mi     2%      35  4.9M    0%   /System/Volumes/iSCPreboot
/dev/disk1s3     500Mi   924Ki   483Mi     1%      48  4.9M    0%   /System/Volumes/Hardware
/dev/disk3s5     228Gi   141Gi    67Gi    68%    4.1M  704M    1%   /System/Volumes/Data
map auto_home      0Bi     0Bi     0Bi   100%       0     0     -   /System/Volumes/Data/home
/dev/disk3s3     228Gi   1.9Gi    67Gi     3%      38  704M    0%   /Volumes/Recovery
jon@mac ⚡️ ls -la /Users/jon/coding-project-2
total 0
drwxr-xr-x    2 jon  staff    64 Nov  5 18:28 .
drwxr-xr-x+ 101 jon  staff  3232 Nov  5 18:22 ..
jon@mac ⚡️  
```

clearing cache again since AI says npx is the thing thats called not pnpm

```
jon@mac ⚡️ rm -rf ~/.npm/_npx
jon@mac ⚡️ npx shadcn@latest init
Need to install the following packages:
shadcn@3.5.0
Ok to proceed? (y) y

npm warn deprecated node-domexception@1.0.0: Use your platform's native DOMException instead
✔ The path /Users/jon/coding-project-2 does not contain a package.json file.
  Would you like to start a new project? › Next.js 15
✔ What is your project named? … YourApplicant
⠸ Creating a new Next.js 15 project. This may take a few minutes.
Something went wrong creating a new Next.js project. Please try again.
jon@mac ⚡️ 
```


lol. it was because of capital letters.

```
Something went wrong creating a new Next.js project. Please try again.
jon@mac ⚡️ npx create-next-app@15 YourApplicant --typescript --tailwind --eslint --app --no-src-dir --turbopack
Could not create a project called "YourApplicant" because of npm naming restrictions:
    * name can no longer contain capital letters
jon@mac ⚡️ 
```

it works now

```
jon@mac ⚡️ npx shadcn@latest init
✔ The path /Users/jon/coding-project-2 does not contain a package.json file.
  Would you like to start a new project? › Next.js 15
✔ What is your project named? … your-applicant
✔ Creating a new Next.js 15 project.
✔ Which color would you like to use as the base color? › Neutral
✔ Writing components.json.
✔ Checking registry.
✔ Updating CSS variables in app/globals.css
✔ Installing dependencies.
✔ Created 1 file:
  - lib/utils.ts

Success! Project initialization completed.
You may now add components.

jon@mac ⚡️ 

```

**Comment by drriguz** [comment]
Same issue when creating app in MacOs:

```
pnpm dlx shadcn@latest create --preset "https://ui.shadcn.com/init?base=radix&style=mira&baseColor=zinc&theme=emerald&iconLibrary=lucide&font=inter&menuAccent=subtle&menuColor=default&radius=none&template=vite" --template vite
✔ What is your project named? … y-admin
⠸ Creating a new Vite project. This may take a few minutes.
```

nothing happens and hangs forever

**Comment by Derek-Croissant** [comment]
I encountered a similar problem. In the end, I skipped the init process, manually installed the relevant dependencies and config items, and then directly ran the add component command. However, I still need to write additional auto scripts to handle internal import errors when installing components.
